######################################################################
# Automatically generated by qmake (1.03a) Sat Mar 15 13:49:04 2003
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = GDsl Netlist Path FMBiPart FMKWayPart \
          FMPart FMPWPart MlPart part Testing
