######################################################################
# Automatically generated by qmake (1.03a) Thu Oct 9 18:29:39 2003
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = vector1 vector2
