######################################################################
# Automatically generated by qmake (1.03a) Sat Mar 15 13:14:16 2003
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = GBPQueue GBTree GDList GMultiSet GStack
