######################################################################
# Automatically generated by qmake (1.03a) Sat Mar 15 13:04:55 2003
######################################################################

TEMPLATE = app
CONFIG += debug
CONFIG -= moc qt 

# Input
SOURCES += main.cpp
INCLUDEPATH += ../../../GDsl
unix:LIBS += -L../../../lib -lGDsl
# INCLUDEPATH += ../../../loki ../../../STLport-4.5.3/stlport
# 
# release {
# unix:LIBS += -L../../../STLport-4.5.3/lib -lstlport_gcc -lpthread
# }
# 
# debug {
# unix:LIBS += -L../../../STLport-4.5.3/lib -lstlport_gcc_stldebug -lpthread
# }
