######################################################################
# Automatically generated by qmake (1.03a) Tue Sep 23 09:44:08 2003
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = GPoint
