######################################################################
# Automatically generated by qmake (1.03a) Sun Apr 6 12:08:10 2003
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = GDsl Netlist Netlist2 Netlist3 vrw Contract \
          FMPart FMPart2 FMPart3 FMPart4 MlPart MlPart2 MlPart4 MlPart7 \
          FMPWPart MlPWPart FMFIFO MlKWayFIFO \
          FMKWayTop FMKWayPart MlFIFO Removal Removal2

# Additional tests
# SUBDIRS += STLport
