FMKWayPartMgrBase Class Reference
FMKWayPartMgrBase Class Reference
Multi-Way Partitioner Core Engine
#include <FMKWayPartMgrBase.hpp>
Public Member Functions
unsigned int getNumPartitions () const
int getCostModel () const
void setDiff (const boost::array< int, 64 > &diff)
void setDiff2 (const boost::array< int, 64 > &diff)
const boost::array< int, 64 > & getDiff () const
boost::array< int, 64 > & getDiff ()
void initDiff (const std::vector< unsigned char > &part)
bool checkBalanceOk (const std::vector< unsigned char > &part)
unsigned int cutCost (const std::vector< unsigned char > &part) const
virtual void printDiff () const
Protected Member Functions
FMKWayPartMgrBase (const FMParam &param)
~FMKWayPartMgrBase ()
KWayConstrMgr3 & getConstraintMgr ()
const KWayConstrMgr3 & getConstraintMgr () const
void initPart (std::vector< unsigned char > &part)
virtual void initBase ()
Protected Attributes
unsigned int _K
int _cm
boost::array< int, _M > _diff
KWayConstrMgr3 _constraintMgr
Static Protected Attributes
static const unsigned int _M = 64
Detailed Description
FM K-Way Partitioning Manager Utility. Provide service such that calculate cut cost, constraint checking etc. This class could also be the base class of the multilevel k-way partitioning manager.
Constructor & Destructor Documentation
FMKWayPartMgrBase::FMKWayPartMgrBase (const FMParam & param) [protected]
Constructor
References _cm, _K, FMPartMgrBase::getNetlist(), and NetlistBase::setCostModel().
FMKWayPartMgrBase::~FMKWayPartMgrBase () [inline, protected]
Destructor
Member Function Documentation
bool FMKWayPartMgrBase::checkBalanceOk (const std::vector< unsigned char > & part)
Returns:
true if the balance condition of the solution is OK. Take O(n) time.
References FMBiPartMgrBase::getConstraintMgr(), and BiConstrMgrBase::satisfiedAll().
unsigned int FMKWayPartMgrBase::cutCost (const std::vector< unsigned char > & part) const [virtual]
Returns:
the cut cost according to the defined cost model. Take O(n) time.
Implements FMPartMgrBase.
KWayConstrMgr3& FMKWayPartMgrBase::getConstraintMgr () [inline, protected]
Returns:
the constraint Manger
References _constraintMgr.
const KWayConstrMgr3& FMKWayPartMgrBase::getConstraintMgr () const [inline, protected]
Returns:
the constraint Manger
References _constraintMgr.
int FMKWayPartMgrBase::getCostModel () const [inline]
Returns:
the cost model.
References _cm.
Referenced by FMKWayPartCore4::updateMove(), and FMKWayPartCore::updateMove().
const boost::array<int,64>& FMKWayPartMgrBase::getDiff () const [inline]
(For Multilevel code only)
Returns:
the diff structure.
References _diff.
boost::array<int,64>& FMKWayPartMgrBase::getDiff () [inline]
(For Multilevel code only)
Returns:
the diff structure.
References _diff.
unsigned int FMKWayPartMgrBase::getNumPartitions () const [inline]
Returns:
the number of partitions.
Reimplemented from FMPartMgrBase.
References _K.
Referenced by FMKWayPartComm::FMKWayPartComm(), FMKWayPartCore4::FMKWayPartCore4(), FMKWayPartComm::initGainHEdge(), FMKWayPartComm::initGainKMinus1(), FMKWayPartComm::initGainSOED(), FMKWayPartCore4::pushBack4(), FMKWayPartCore4::updateMove(), FMKWayPartComm::updateMove2PinNet(), FMKWayPartComm::updateMove2PinNet4(), FMKWayPartCore4::updateMove4(), FMKWayPartComm::updateMoveGeneralNetCommKMinus1(), FMKWayPartComm::updateMoveGeneralNetHEdge4(), FMKWayPartComm::updateMoveGeneralNetKMinus14(), FMKWayPartComm::updateMoveGeneralNetSOED4(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore4::updateMoveSOED(), FMKWayPartCore::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
void FMKWayPartMgrBase::initBase () [protected, virtual]
Initialization after the creation of this class, but before the iteration (i.e. doPartitionOne())
Reimplemented from FMPartMgrBase.
void FMKWayPartMgrBase::initDiff (const std::vector< unsigned char > & part)
Returns:
initial difference between the partitions. Take O(n) time.
References FMBiPartMgrBase::_diff.
void FMKWayPartMgrBase::initPart (std::vector< unsigned char > & part) [protected]
Obtain initial feasible solution
References FMPartMgrBase::_cellList, FMBiPartMgrBase::_diff, FMPartMgrBase::getNumCells(), Cell::getWeight(), and Cell::isFixed().
void FMKWayPartMgrBase::setDiff (const boost::array< int, 64 > & diff)
(For Multilevel code only) Set diff.
Member Data Documentation
int FMKWayPartMgrBase::_cm [protected]
Cost Model
Referenced by FMKWayPartMgrBase(), and getCostModel().
KWayConstrMgr3 FMKWayPartMgrBase::_constraintMgr [protected]
manage the balance constraints
Referenced by getConstraintMgr().
boost::array<int,_M> FMKWayPartMgrBase::_diff [protected]
diff cell weight
Referenced by getDiff().
unsigned int FMKWayPartMgrBase::_K [protected]
number of partitions
Referenced by FMKWayPartMgrBase(), and getNumPartitions().
The documentation for this class was generated from the following files:
FMKWayPartMgrBase.hpp
FMBiPartMgrBase.cpp
FMKWayPartMgrBase.cpp