PinForNetCursorTmpl< Net_, Pin_ > Class Template Reference
PinForNetCursorTmpl< Net_, Pin_ > Class Template Reference
Data Modeling Group.
#include <NetlistBase.hpp>
Public Member Functions
PinForNetCursorTmpl (Net_ &n)
unsigned int count () const
bool hasNext () const
Pin_ & getNext ()
Detailed Description
template<class Net_, class Pin_ = Pin>
class PinForNetCursorTmpl< Net_, Pin_ >
Cursor to traverse all the pins of one net/cell
Constructor & Destructor Documentation
template<class Net_ , class Pin_ = Pin> PinForNetCursorTmpl< Net_, Pin_ >::PinForNetCursorTmpl (Net_ & n) [inline]
Constructor
Member Function Documentation
template<class Net_ , class Pin_ = Pin> unsigned int PinForNetCursorTmpl< Net_, Pin_ >::count () const [inline]
Returns:
the number of pins remain to traverse.
Referenced by NetlistBase::cutCost(), FMBiPartComm::initGain(), FMKWayPartComm::initGainHEdge(), FMKWayPartComm::initGainKMinus1(), FMKWayPartComm::initGainSOED(), NetlistBase::printNetDist(), NetlistBaseTestCase::testCellCursor(), FMBiPartCore4::updateMove(), FMBiPartCore::updateMove(), FMKWayPartComm::updateMove2PinNet(), FMBiPartComm::updateMove2PinNet(), FMKWayPartComm::updateMove2PinNet4(), FMBiPartComm::updateMoveGeneralNet(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore4::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore4::updateMoveSOED(), FMKWayPartCore::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
template<class Net_ , class Pin_ = Pin> Pin_& PinForNetCursorTmpl< Net_, Pin_ >::getNext () [inline]
Returns:
the next pin. Precondition: there exist the next item.
Reimplemented in CellCursorTmpl< Cell_, Net_, Pin_ >.
References PinForNetCursorTmpl< Net_, Pin_ >::hasNext().
Referenced by NetlistBase::checkOk(), LayerAssignmentServ::doAssignment(), and NetlistBaseTestCase::testPinCursor().
template<class Net_ , class Pin_ = Pin> bool PinForNetCursorTmpl< Net_, Pin_ >::hasNext () const [inline]
Returns:
true if there exist a next item.
Referenced by NetlistBase::checkOk(), Netlist::clusterSize(), NetlistBase::cutCost(), LayerAssignmentServ::doAssignment(), PinForNetCursorTmpl< Net_, Pin_ >::getNext(), NetlistBase::HyperEdgeCost(), FMBiPartComm::initGain(), Netlist::markZeroPinNets(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), CycleRemovalServ::selectIndependentNets(), Netlist::setFixedNets(), NetlistBaseTestCase::testCellCursor(), NetlistBaseTestCase::testPinCursor(), FMBiPartCore::updateMove(), FMBiPartComm::updateMoveGeneralNet(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore::updateMoveSOED(), FMKWayPartCore::updateMoveSOEDCore(), and NetlistBase::writeHMetis().
The documentation for this class was generated from the following file:
NetlistBase.hpp