FMBiPartMgrBase Class Reference
FMBiPartMgrBase Class Reference
Bi-partitioner Core Engine
#include <FMBiPartMgrBase.hpp>
Public Member Functions
unsigned int getNumPartitions () const
unsigned int getCostModel () const
void setDiff (const int *diff)
void setDiff2 (const int *diff)
const int * getDiff () const
int * getDiff ()
void initDiff (const std::vector< unsigned char > &part)
bool checkBalanceOk (const std::vector< unsigned char > &part)
unsigned int cutCost (const std::vector< unsigned char > &part) const
virtual void printDiff () const
Protected Member Functions
FMBiPartMgrBase (const FMParam &param)
virtual ~FMBiPartMgrBase ()
BiConstrMgr3 & getConstraintMgr ()
const BiConstrMgr3 & getConstraintMgr () const
void initPart (std::vector< unsigned char > &part)
virtual void initBase ()
Protected Attributes
int _diff [2]
BiConstrMgr3 _constraintMgr
Detailed Description
FM Bi-partitioning Manager Utility. Provide service such that calculate cut cost, constraint checking etc. This class could also be the base class of the multilevel bi-partitioning manager.
Constructor & Destructor Documentation
FMBiPartMgrBase::FMBiPartMgrBase (const FMParam & param) [protected]
Constructor
Long function is bad. It makes other people difficult to understand the code and hard to maintain. I sometimes also write long functions. The excuse usually is the gain of run-time performance, even the function only contribute a very small portion of total run-time. Since C++ provides the inline function method, it should not be an excuse anymore. Constructor
virtual FMBiPartMgrBase::~FMBiPartMgrBase () [inline, protected, virtual]
Destructor
Member Function Documentation
bool FMBiPartMgrBase::checkBalanceOk (const std::vector< unsigned char > & part)
Returns:
true if the balance condition of the solution is OK. Take O(n) time.
unsigned int FMBiPartMgrBase::cutCost (const std::vector< unsigned char > & part) const [virtual]
Returns:
the cutCost. Take O(n) time.
Implements FMPartMgrBase.
BiConstrMgr3& FMBiPartMgrBase::getConstraintMgr () [inline, protected]
Returns:
the constraint Manger
References _constraintMgr.
Referenced by FMKWayPartMgrBase::checkBalanceOk(), and setDiff2().
const BiConstrMgr3& FMBiPartMgrBase::getConstraintMgr () const [inline, protected]
Returns:
the constraint Manger
References _constraintMgr.
unsigned int FMBiPartMgrBase::getCostModel () const [inline]
Returns:
the cost model (always 0 for this version).
const int* FMBiPartMgrBase::getDiff () const [inline]
(For Multilevel code only)
Returns:
the diff structure.
References _diff.
int* FMBiPartMgrBase::getDiff () [inline]
(For Multilevel code only)
Returns:
the diff structure.
References _diff.
unsigned int FMBiPartMgrBase::getNumPartitions () const [inline]
Returns:
the number of partitions (always 2 for this version).
Reimplemented from FMPartMgrBase.
void FMBiPartMgrBase::initBase () [protected, virtual]
Initialization after the creation of this class, but before the iteration (i.e. doPartitionOne())
Reimplemented from FMPartMgrBase.
void FMBiPartMgrBase::initDiff (const std::vector< unsigned char > & part)
Returns:
initial difference between the partitions. Take O(n) time.
void FMBiPartMgrBase::setDiff (const int * diff)
(For Multilevel code only) Set diff.
References _diff.
void FMBiPartMgrBase::setDiff2 (const int * diff)
(For Multilevel code only) Set diff.
References _diff, getConstraintMgr(), FMPartMgrBase::getMaxDiff(), and FMPartMgrBase::setMaxDiff().
Member Data Documentation
BiConstrMgr3 FMBiPartMgrBase::_constraintMgr [protected]
manage the balance constraints
Referenced by getConstraintMgr().
int FMBiPartMgrBase::_diff[2] [protected]
diff cell weight btw two parts
Referenced by getDiff(), FMKWayPartMgrBase::initDiff(), FMKWayPartMgrBase::initPart(), setDiff(), and setDiff2().
The documentation for this class was generated from the following files:
FMBiPartMgrBase.hpp
FMBiPartMgrBase.cpp