FMKWayGainMgr2 Class Reference
FMKWayGainMgr2 Class Reference
Multi-Way Partitioner Core Engine
#include <FMKWayGainMgr2.hpp>
Public Member Functions
FMKWayGainMgr2 (const FMParam &param)
void init (const std::vector< unsigned char > &part, std::vector< short > *gain)
Vertex * select (FMMoveInfo &moveInfo, const std::vector< unsigned char > &part, KWayConstrMgr3 &constrMgr)
int getGain (const FMMoveInfo &moveInfo) const
void updateMove (const FMMoveInfo &moveInfo, const short *=0)
void updateNeighbor (unsigned int whichPart, unsigned int i_w, const short *deltaGain)
void pushBack (unsigned int whichPart, unsigned int i_w, const short *gain)
void updateGain (const std::vector< unsigned char > &part, std::vector< short > *gain)
Protected Member Functions
unsigned int getNumPartitions () const
Protected Attributes
Netlist & _H
unsigned int _K
VertexPQ _gainBucket [_M]
VertexPQCur _gainBucketCur [_M]
std::vector< Vertex > _vertexArray [_M]
Cell *const _cellList
Detailed Description
FM Multi-way Partitioning Gain Manager. This class responsible for maintaining the gain bucket structures and helps to select the best vertex. In this version, K bucket array are used, one for each partition.
See also:
FMBiGainMgr2.
Constructor & Destructor Documentation
FMKWayGainMgr2::FMKWayGainMgr2 (const FMParam & param)
Constructor
References FMParam::_cm, _gainBucket, _gainBucketCur, _H, _K, _vertexArray, GBPQueueCursor< BPQNode >::associate(), NetlistBase::getMaxDegree(), NetlistBase::getNumCells(), getNumPartitions(), and GBPQueue< BPQNode >::setUp().
Member Function Documentation
int FMKWayGainMgr2::getGain (const FMMoveInfo & moveInfo) const [inline]
Returns:
the gain of vertex if it moves from fromPart to toPart
References _gainBucket, FMMoveInfo::_i_v, FMMoveInfo::_toPart, _vertexArray, and GBPQueue< BPQNode >::getKey().
unsigned int FMKWayGainMgr2::getNumPartitions () const [inline, protected]
Returns:
the number of partitions.
References _K.
Referenced by FMKWayGainMgr2(), pushBack(), updateMove(), FMKWayGainMgr3::updateNeighbor(), and updateNeighbor().
void FMKWayGainMgr2::init (const std::vector< unsigned char > & part, std::vector< short > * gain)
Setup the gain bucket structure
Referenced by updateGain().
void FMKWayGainMgr2::pushBack (unsigned int whichPart, unsigned int i_w, const short * gain) [inline]
Push back the vertices of cell i_w to the gain manager.
References _gainBucket, _vertexArray, getNumPartitions(), and GBPQueue< BPQNode >::pushBack().
Vertex* FMKWayGainMgr2::select (FMMoveInfo & moveInfo, const std::vector< unsigned char > & part, KWayConstrMgr3 & constrMgr)
Returns:
the next "best" vertex that satisfies all constraints when it is moved. Return also move from where to where.
void FMKWayGainMgr2::updateGain (const std::vector< unsigned char > & part, std::vector< short > * gain) [inline]
Update the gain structure according to the current gain.
References init().
void FMKWayGainMgr2::updateMove (const FMMoveInfo & moveInfo, const short * = 0) [inline]
Update the changes according to the move of vertex v from fromPart to toPart
References FMMoveInfo::_fromPart, _gainBucket, FMMoveInfo::_i_v, _vertexArray, GBPQueue< BPQNode >::detach(), and getNumPartitions().
void FMKWayGainMgr2::updateNeighbor (unsigned int whichPart, unsigned int i_w, const short * deltaGain) [inline]
Update the gain changes of the neighbor vertex in whichPart
Parameters:
whichPart in which partition
i_w the affected neighbor vertex
deltaGain the gain changes
Reimplemented in FMKWayGainMgr3.
References _cellList, _gainBucket, _vertexArray, getNumPartitions(), and GBPQueue< BPQNode >::modifyKeyLIFOBy().
Member Data Documentation
Cell* const FMKWayGainMgr2::_cellList [protected]
Cell array offset
Referenced by FMKWayGainMgr3::updateNeighbor(), and updateNeighbor().
VertexPQ FMKWayGainMgr2::_gainBucket[_M] [protected]
gain bucket for each partition
Referenced by FMKWayGainMgr2(), getGain(), pushBack(), updateMove(), FMKWayGainMgr3::updateNeighbor(), and updateNeighbor().
VertexPQCur FMKWayGainMgr2::_gainBucketCur[_M] [protected]
gain bucket cursor
Referenced by FMKWayGainMgr2().
Netlist& FMKWayGainMgr2::_H [protected]
netlist hypergraph
Referenced by FMKWayGainMgr2().
unsigned int FMKWayGainMgr2::_K [protected]
number of partitions
Referenced by FMKWayGainMgr2(), and getNumPartitions().
std::vector<Vertex> FMKWayGainMgr2::_vertexArray[_M] [protected]
keep the data struct for the algo.
Referenced by FMKWayGainMgr2(), getGain(), pushBack(), updateMove(), FMKWayGainMgr3::updateNeighbor(), and updateNeighbor().
The documentation for this class was generated from the following files:
FMKWayGainMgr2.hpp
FMKWayGainMgr2.cpp