GDList< DNode > Class Template Reference
GDList< DNode > Class Template Reference
Data Structure Group
#include <GDList.hpp>
Public Member Functions
GDList ()
bool isEmpty () const
void clear ()
DNode & first ()
DNode & last ()
const DNode & first () const
const DNode & last () const
void pushFront (DNode &ptr)
void pushBack (DNode &ptr)
void pushRandom (DNode &ptr)
DNode & popFront ()
DNode & popBack ()
void popFrontFast ()
void popBackFast ()
void concat (GDList< DNode > &L)
bool isValid () const
Static Public Member Functions
static void detach (DNode &ptr)
Friends
class GDListCursor< DNode >
class GDListConstCursor< DNode >
class GBPQueue< DNode >
class GBPQueue2< DNode >
Detailed Description
template<class DNode>
class GDList< DNode >
A Doubly-linked List class. This class simply contains a link of node's. By adding a dummy node (sentinel) nil, deleting a node is extremely fast (see "Introduction to Algorithm"). This class does not keep the length information as it is not necessary for the FM algorithm. This saves memory and run-time to update the length information. Note that this class does not own the list node. They are supplied by the caller in order to better reuse the nodes.
From "Introduction to Algorithm":
A sentinel is a dummy object that allows us to simplify boundary conditions. For example, suppose that we provide with list L an object nil[L] that represents NIL but has all the fields of the other list elements. Wherever we have a reference to NIL in list code, we replace it by a reference to the sentinel nil[L]. As shown in Figure 11.4, this turns a regular doubly linked list into a circular list, with the sentinel nil[L] placed between the head and tail; the field next[nil[L]] points to the head of the list, and prev[nil[L]] points to the tail. Similarly, both the next field of the tail and the prev field of the head point to nil[L]. Since next[nil[L]] points to the head, we can eliminate the attribute head[L] altogether, replacing references to it by references to next[nil[L]]. An empty list consists of just the sentinel, since both next[nil[L]] and prev[nil[L]] can be set to nil[L].
Constructor & Destructor Documentation
template<class DNode> GDList< DNode >::GDList () [inline]
Constructor
Member Function Documentation
template<class DNode> void GDList< DNode >::clear () [inline]
Reset to empty list.
Referenced by GDList< Vertex >::concat(), CycleRemovalServ::setup(), and GDListTestCase::testConstCursor().
template<class DNode> void GDList< DNode >::concat (GDList< DNode > & L) [inline]
Concatenate L to the end of this list. L becomes an empty list after the concatenation.
Referenced by GMultiSet< T >::ascendingOrder(), GMultiSet< T >::decendingOrder(), CycleRemovalServ::doRemove(), Netlist::initWeightList(), GBPQueue< BPQNode >::pushTo(), and CycleRemovalServ::verifyOK().
template<class DNode> static void GDList< DNode >::detach (DNode & ptr) [inline, static]
Detach item from this list. Precondition: list contains the node
Referenced by GBPQueue< BPQNode >::decreaseKeyBy(), GBPQueue< BPQNode >::decreaseKeyLIFOBy(), GBPQueue< BPQNode >::detach(), GBPQueue< BPQNode >::increaseKeyBy(), GBPQueue< BPQNode >::increaseKeyLIFOBy(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), CycleRemovalServ::selectIndependentNets(), and GDListTestCase::testCursor().
template<class DNode> const DNode& GDList< DNode >::first () const [inline]
Returns:
the first item. Precondition: list is not empty
template<class DNode> DNode& GDList< DNode >::first () [inline]
Returns:
the first item. Precondition: list is not empty
Referenced by GDList< Vertex >::concat().
template<class DNode> bool GDList< DNode >::isEmpty () const [inline]
Returns:
true if list is empty.
Referenced by GDList< Vertex >::concat(), CycleRemovalServ::doRemove(), GDList< Vertex >::first(), GDList< Vertex >::last(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), GDList< Vertex >::popBack(), GDList< Vertex >::popBackFast(), GDList< Vertex >::popFront(), GDList< Vertex >::popFrontFast(), CycleRemovalServ::selectIndependentNets(), GDListTestCase::testConstCursor(), GDListTestCase::testCursor(), GDListTestCase::testPushPop(), and CycleRemovalServ::verifyOK().
template<class DNode> bool GDList< DNode >::isValid () const [inline]
Returns:
true if the list is valid. Take O(n) time
Referenced by CycleRemovalServ::verifyOK().
template<class DNode> DNode& GDList< DNode >::last () [inline]
Returns:
the last item. Precondition: list is not empty
Referenced by GDList< Vertex >::concat().
template<class DNode> const DNode& GDList< DNode >::last () const [inline]
Returns:
the last item. Precondition: list is not empty
template<class DNode> DNode& GDList< DNode >::popBack () [inline]
Pop an item from the end of the list. Precondition: list is not empty
Referenced by Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), and CycleRemovalServ::selectIndependentNets().
template<class DNode> void GDList< DNode >::popBackFast () [inline]
Pop an item from the end of the list. Precondition: list is not empty
template<class DNode> DNode& GDList< DNode >::popFront () [inline]
Pop an item from the front of the list. Precondition: list is not empty
Referenced by CycleRemovalServ::handleSink(), CycleRemovalServ::handleSrc(), Netlist::minimumNetCover2(), and GDListTestCase::testPushPop().
template<class DNode> void GDList< DNode >::popFrontFast () [inline]
Pop an item from the front of the list. Precondition: list is not empty
template<class DNode> void GDList< DNode >::pushBack (DNode & ptr) [inline]
Insert item at the end of this list Precondtion: list does not contain the node
Referenced by CycleRemovalServ::handleNextBest(), CycleRemovalServ::handleSrc(), GMultiSet< T >::insert(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover2(), GDList< Vertex >::pushRandom(), CycleRemovalServ::selectIndependentNets(), GDListTestCase::testConstCursor(), GDListTestCase::testCursor(), and GDListTestCase::testPushPop().
template<class DNode> void GDList< DNode >::pushFront (DNode & ptr) [inline]
Insert item at the front of this list. Precondition: list does not contain the node
Referenced by CycleRemovalServ::handleSink(), GMultiSet< T >::insertFront(), and GDList< Vertex >::pushRandom().
template<class DNode> void GDList< DNode >::pushRandom (DNode & ptr) [inline]
Arbitrarily put item at the front or at the end of this list Precondition: list does not contain the node
Referenced by CycleRemovalServ::setup().
The documentation for this class was generated from the following file:
GDList.hpp