GBPQueue2Cursor< BPQNode > Class Template Reference
GBPQueue2Cursor< BPQNode > Class Template Reference
Data Structure Group
#include <GBPQueue2.hpp>
Public Member Functions
GBPQueue2Cursor ()
GBPQueue2Cursor (GBPQueue2< BPQNode > &BPQ)
void associate (GBPQueue2< BPQNode > &BPQ)
bool hasNext () const
void reset ()
unsigned int getKey () const
unsigned int getSecondKey () const
BPQNode & getNext ()
Detailed Description
template<class BPQNode>
class GBPQueue2Cursor< BPQNode >
Bounded Priority Queue2 Cursor. Traverse the queue in descending order. Detaching queue items may invalidate the cursor because the cursor make a copy of current key.
Constructor & Destructor Documentation
template<class BPQNode> GBPQueue2Cursor< BPQNode >::GBPQueue2Cursor () [inline]
Default Constructor
template<class BPQNode> GBPQueue2Cursor< BPQNode >::GBPQueue2Cursor (GBPQueue2< BPQNode > & BPQ) [inline]
Constructor.
Member Function Documentation
template<class BPQNode> void GBPQueue2Cursor< BPQNode >::associate (GBPQueue2< BPQNode > & BPQ) [inline]
Associate to the queue BPQ and reset the cursor.
References GBPQueue2Cursor< BPQNode >::reset().
template<class BPQNode> unsigned int GBPQueue2Cursor< BPQNode >::getKey () const [inline]
Returns:
the key of the next node (without offset!)
template<class BPQNode> BPQNode& GBPQueue2Cursor< BPQNode >::getNext () [inline]
Returns:
the next item. Precondition: next item exists.
References GBPQueue2Cursor< BPQNode >::hasNext().
template<class BPQNode> unsigned int GBPQueue2Cursor< BPQNode >::getSecondKey () const [inline]
Returns:
the key of the next node (without offset!)
template<class BPQNode> bool GBPQueue2Cursor< BPQNode >::hasNext () const [inline]
Returns:
true if there is a next item.
Referenced by GBPQueue2Cursor< BPQNode >::getNext().
template<class BPQNode> void GBPQueue2Cursor< BPQNode >::reset () [inline]
Reset the cursor to the first position.
Referenced by GBPQueue2Cursor< BPQNode >::associate().
The documentation for this class was generated from the following file:
GBPQueue2.hpp