GBPQueueCursor< BPQNode > Class Template Reference
GBPQueueCursor< BPQNode > Class Template Reference
Data Structure Group
#include <GBPQueue.hpp>
Public Member Functions
GBPQueueCursor ()
GBPQueueCursor (GBPQueue< BPQNode > &BPQ)
void associate (GBPQueue< BPQNode > &BPQ)
void reset ()
bool hasNext () const
unsigned int getRelKey () const
BPQNode & getNext ()
Detailed Description
template<class BPQNode>
class GBPQueueCursor< BPQNode >
Bounded Priority Queue Cursor. Traverse the queue in descending order. Detaching queue items may invalidate the cursor because the cursor makes a copy of current key.
Constructor & Destructor Documentation
template<class BPQNode> GBPQueueCursor< BPQNode >::GBPQueueCursor () [inline]
Default Constructor
template<class BPQNode> GBPQueueCursor< BPQNode >::GBPQueueCursor (GBPQueue< BPQNode > & BPQ) [inline]
Constructor.
Member Function Documentation
template<class BPQNode> void GBPQueueCursor< BPQNode >::associate (GBPQueue< BPQNode > & BPQ) [inline]
Associate to the queue BPQ and reset the cursor.
Referenced by FMBiGainMgr::FMBiGainMgr(), FMBiGainMgr2::FMBiGainMgr2(), FMKWayGainMgr2::FMKWayGainMgr2(), and FMKWayGainMgr4::FMKWayGainMgr4().
template<class BPQNode> BPQNode& GBPQueueCursor< BPQNode >::getNext () [inline]
Returns:
the next item. Precondition: next item exists.
Referenced by FMBiGainMgr2::select(), FMKWayGainMgr4::select(), and GBPQueueTestCase::testCursors().
template<class BPQNode> unsigned int GBPQueueCursor< BPQNode >::getRelKey () const [inline]
Returns:
the key of the current node (without offset!). For comparsion purpose only.
Referenced by FMBiGainMgr2::select().
template<class BPQNode> bool GBPQueueCursor< BPQNode >::hasNext () const [inline]
Returns:
true if there is a next item.
Referenced by GBPQueueCursor< Vertex >::getNext(), FMKWayGainMgr4::select(), and GBPQueueTestCase::testCursors().
template<class BPQNode> void GBPQueueCursor< BPQNode >::reset () [inline]
Reset the cursor to the first position.
Referenced by GBPQueueCursor< Vertex >::associate(), FMBiGainMgr2::select(), and FMKWayGainMgr4::select().
The documentation for this class was generated from the following file:
GBPQueue.hpp