GBPQueue2< BPQNode > Class Template Reference
GBPQueue2< BPQNode > Class Template Reference
Data Structure Group
#include <GBPQueue2.hpp>
Public Member Functions
GBPQueue2 (int a, int b, int a2, int b2)
~GBPQueue2 ()
void setUp (int a, int b, int a2, int b2)
int getKey (const BPQNode &it) const
int getMax () const
bool isEmpty () const
void makeDummy ()
void clear ()
void pushBack (BPQNode &it, int k, int k2)
void pushFront (BPQNode &it, int k, int k2)
void pushRandom (BPQNode &it, int k, int k2)
void pushBackFast (BPQNode &it, int k, int k2)
void pushFrontFast (BPQNode &it, int k, int k2)
void pushRandomFast (BPQNode &it, int k, int k2)
void resync ()
BPQNode & popFront ()
void pop ()
BPQNode & top ()
void decreaseKeyLIFO (BPQNode &it, int k, int k2)
void increaseKeyLIFO (BPQNode &it, int k, int k2)
void modifyKeyLIFO (BPQNode &it, int k, int k2)
void decreaseKey (BPQNode &it)
void increaseKey (BPQNode &it)
void decreaseKeyLIFOBy (BPQNode &it, unsigned int m, int m2)
void increaseKeyLIFOBy (BPQNode &it, unsigned int m, int m2)
void modifyKeyLIFOBy (BPQNode &it, int m, int m2)
void detach (BPQNode &it)
void pushTo (GDList< BPQNode > &list)
Friends
class GBPQueue2Cursor< BPQNode >
class GBPQueue2ConstCursor< BPQNode >
Detailed Description
template<class BPQNode>
class GBPQueue2< BPQNode >
(Experimental) Bounded Priority Queue with secondary key.
Constructor & Destructor Documentation
template<class BPQNode> GBPQueue2< BPQNode >::GBPQueue2 (int a, int b, int a2, int b2) [inline]
Constructor.
Parameters:
a lower bound
b upper bound
a2 lower bound of second key
b2 upper bound of second key Precondition: a <= b
References GBPQueue2< BPQNode >::setUp().
template<class BPQNode> GBPQueue2< BPQNode >::~GBPQueue2 () [inline]
Destructor.
Member Function Documentation
template<class BPQNode > void GBPQueue2< BPQNode >::clear () [inline]
Reset the PQ.
template<class BPQNode > void GBPQueue2< BPQNode >::decreaseKey (BPQNode & it) [inline]
Decrease key by one. Precondition: PQ contains it; a <= k <= b
template<class BPQNode > void GBPQueue2< BPQNode >::decreaseKeyLIFO (BPQNode & it, int k, int k2) [inline]
Decrease the key of item to k in Last-In-First-Out fashion. Precondition: PQ contains it; a <= k <= b. Note that order of items with same key will not preserved. For FM algorithm, this is a prefered behavior.
template<class BPQNode > void GBPQueue2< BPQNode >::decreaseKeyLIFOBy (BPQNode & it, unsigned int m, int m2)
Decrease key by m. Precondition: PQ contains it. Note that order of items with same key will not preserved. For FM algorithm, this is a prefered behavior.
template<class BPQNode > void GBPQueue2< BPQNode >::detach (BPQNode & it) [inline]
Detach the item from this queue. Precondition: PQ contains it
template<class BPQNode> int GBPQueue2< BPQNode >::getKey (const BPQNode & it) const [inline]
Returns:
the key of it.
template<class BPQNode> int GBPQueue2< BPQNode >::getMax () const [inline]
Returns:
the max value.
template<class BPQNode > void GBPQueue2< BPQNode >::increaseKey (BPQNode & it) [inline]
Increase key by one. Precondition: PQ contains it; a <= k <= b
template<class BPQNode > void GBPQueue2< BPQNode >::increaseKeyLIFO (BPQNode & it, int k, int k2) [inline]
Increase the key of item to k in Last-In-First-Out fashion. Precondition: PQ contains it. Note that order of items with same key will not preserved. For FM algorithm, this is a prefered behavior.
template<class BPQNode > void GBPQueue2< BPQNode >::increaseKeyLIFOBy (BPQNode & it, unsigned int m, int m2)
Increase key by m. Precondition: PQ contains it. Note that order of items with same key will not preserved. For FM algorithm, this is a prefered behavior.
template<class BPQNode> bool GBPQueue2< BPQNode >::isEmpty () const [inline]
Returns:
true if the PQ is empty.
template<class BPQNode> void GBPQueue2< BPQNode >::makeDummy () [inline]
Make dummy
template<class BPQNode > void GBPQueue2< BPQNode >::modifyKeyLIFO (BPQNode & it, int k, int k2) [inline]
Modify the key of item to k in Last-In-First-Out fashion. Precondition: PQ contains it. Note that order of items with same key will not preserved. For FM algorithm, this is a prefered behavior.
References GBPQueue2ConstCursor< BPQNode >::getKey().
template<class BPQNode > void GBPQueue2< BPQNode >::modifyKeyLIFOBy (BPQNode & it, int m, int m2) [inline]
Modify key by m. Note that order of items with same key will not preserved. For FM algorithm, this is a prefered behavior.
template<class BPQNode > void GBPQueue2< BPQNode >::pop () [inline]
Pop an item with highest key without returning the item. Precondition: PQ is not empty.
template<class BPQNode > BPQNode & GBPQueue2< BPQNode >::popFront () [inline]
Pop an item with highest key. Precondition: PQ is not empty.
template<class BPQNode > void GBPQueue2< BPQNode >::pushBack (BPQNode & it, int k, int k2) [inline]
Insert item at the end of this queue. Precondition: PQ does not contain it; a <= k <= b.
template<class BPQNode > void GBPQueue2< BPQNode >::pushBackFast (BPQNode & it, int k, int k2) [inline]
Insert item at the end of this queue without update the max value. Call resync() or resyncFast() after calling this method. Precondition: PQ does not contain it; a <= k <= b.
template<class BPQNode > void GBPQueue2< BPQNode >::pushFront (BPQNode & it, int k, int k2) [inline]
Insert item at the front of this queue. Precondition: PQ does not contain it; a <= k <= b.
template<class BPQNode > void GBPQueue2< BPQNode >::pushFrontFast (BPQNode & it, int k, int k2) [inline]
Insert item at the front of this queue without update the max value. Call resync() or resyncFast() after calling this method. Precondition: PQ does not contain it; a <= k <= b.
template<class BPQNode > void GBPQueue2< BPQNode >::pushRandom (BPQNode & it, int k, int k2) [inline]
Arbitrarily put item at the front or at the end of this queue without update the max value. Precondition: PQ does not contain it; a <= k <= b.
template<class BPQNode > void GBPQueue2< BPQNode >::pushRandomFast (BPQNode & it, int k, int k2) [inline]
Arbitrarily put item at the front or at the end of this queue without update the max value. Call resync() or resyncFast() after calling this method. Precondition: PQ does not contain it; a <= k <= b.
template<class BPQNode > void GBPQueue2< BPQNode >::pushTo (GDList< BPQNode > & list) [inline]
Push all the items into a given list. This BPQueue becomes empty after this operation.
template<class BPQNode > void GBPQueue2< BPQNode >::resync () [inline]
Resync the max value
template<class BPQNode > void GBPQueue2< BPQNode >::setUp (int a, int b, int a2, int b2) [inline]
Setup
References GBPQueue< BPQNode >::setUp().
Referenced by GBPQueue2< BPQNode >::GBPQueue2().
template<class BPQNode > BPQNode & GBPQueue2< BPQNode >::top () [inline]
Peek the top item with highest key. Precondtion: PQ is not empty.
The documentation for this class was generated from the following file:
GBPQueue2.hpp