FMBiPartCore Class Reference
FMBiPartCore Class Reference
Bi-partitioner Core Engine
#include <FMBiPartCore.hpp>
Public Member Functions
template<class MoveStruct >
void updateMove (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
Protected Member Functions
FMBiPartCore (const FMParam &param)
virtual ~FMBiPartCore ()
void initGainCore (const std::vector< unsigned char > &part)
void updateNetStatus ()
template<class S >
void updateMove (const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, S &s)
int updateCore (const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo)
Detailed Description
FM Bi-partitioning Manager Core.
Constructor & Destructor Documentation
FMBiPartCore::FMBiPartCore (const FMParam & param) [protected]
Constructor
virtual FMBiPartCore::~FMBiPartCore () [inline, protected, virtual]
Destructor
Member Function Documentation
void FMBiPartCore::initGainCore (const std::vector< unsigned char > & part) [protected]
Setup the initial gain. Take O(n) time.
int FMBiPartCore::updateCore (const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo) [protected]
Update the information after moving i_v
template<class MoveStruct > void FMBiPartCore::updateMove (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
When the cell v is moved from fromPart, update the gains and the gain structures of its neighbors. (c.f. Sarrafzadeh and Wong, page 39)
Parameters:
part current partition solution
ms gain related structre
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, FMMoveInfo::_fromPart, FMBiPartComm::_num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), FMBiPartComm::updateMove2PinNet(), and FMBiPartComm::updateMoveGeneralNet().
template<class S > void FMBiPartCore::updateMove (const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, S & s) [protected]
Update the gain structure given the moving vertex
The documentation for this class was generated from the following files:
FMBiPartCore.hpp
FMBiPartCore.cpp