GBPQueue2ConstCursor< BPQNode > Class Template Reference
GBPQueue2ConstCursor< BPQNode > Class Template Reference
Data Structure Group
#include <GBPQueue2.hpp>
Public Member Functions
GBPQueue2ConstCursor ()
GBPQueue2ConstCursor (const GBPQueue2< BPQNode > &BPQ)
void associate (const GBPQueue2< BPQNode > &BPQ)
bool hasNext () const
void reset ()
unsigned int getKey () const
unsigned int getSecondKey () const
const BPQNode & getNext ()
Detailed Description
template<class BPQNode>
class GBPQueue2ConstCursor< BPQNode >
Bounded Priority Queue Cursor. Traverse the queue in descending order. It is NOT safe to detach queue items during the cursor is active because the cursor make a copy of current key.
Constructor & Destructor Documentation
template<class BPQNode > GBPQueue2ConstCursor< BPQNode >::GBPQueue2ConstCursor () [inline]
Default Constructor
template<class BPQNode > GBPQueue2ConstCursor< BPQNode >::GBPQueue2ConstCursor (const GBPQueue2< BPQNode > & BPQ) [inline]
Constructor.
Member Function Documentation
template<class BPQNode > void GBPQueue2ConstCursor< BPQNode >::associate (const GBPQueue2< BPQNode > & BPQ) [inline]
Associate to the queue BPQ and reset the cursor.
References GBPQueue2ConstCursor< BPQNode >::reset().
template<class BPQNode > unsigned int GBPQueue2ConstCursor< BPQNode >::getKey () const [inline]
Returns:
the key of the next node (without offset!)
Referenced by GBPQueue2< BPQNode >::modifyKeyLIFO().
template<class BPQNode > const BPQNode& GBPQueue2ConstCursor< BPQNode >::getNext () [inline]
Returns:
the next item. Precondition: next item exists.
References GBPQueue2ConstCursor< BPQNode >::hasNext().
template<class BPQNode > unsigned int GBPQueue2ConstCursor< BPQNode >::getSecondKey () const [inline]
Returns:
the second key of the next node (without offset!)
template<class BPQNode > bool GBPQueue2ConstCursor< BPQNode >::hasNext () const [inline]
Returns:
true if there is a next item.
Referenced by GBPQueue2ConstCursor< BPQNode >::getNext().
template<class BPQNode > void GBPQueue2ConstCursor< BPQNode >::reset () [inline]
Reset the cursor to the first position.
Referenced by GBPQueue2ConstCursor< BPQNode >::associate().
The documentation for this class was generated from the following file:
GBPQueue2.hpp