NetlistBase Class Reference
NetlistBase Class Reference
Data Modeling Group.
#include <NetlistBase.hpp>
Public Member Functions
NetlistBase ()
~NetlistBase ()
void clear ()
unsigned int getNumCells () const
unsigned int getNumNets () const
unsigned int getNumPads () const
unsigned int getNumPins () const
unsigned int getMaxDegree () const
unsigned int getId (const Cell &c) const
unsigned int getId (const Net &e) const
Cell & getCell (unsigned int id)
Net & getNet (unsigned int id)
Pin & getPin (unsigned int id)
const Cell & getCell (unsigned int id) const
const Net & getNet (unsigned int id) const
const Pin & getPin (unsigned int id) const
unsigned int getTotalWeight () const
void clrVisitedAllNets () const
void clrFixedAllNets ()
void clrVisitedAllCells () const
bool readHMetis (const char *hgrFileName)
int writeHMetis (const char *fileName) const
int writeDot (const char *fileName) const
bool readNetD (const char *fileName)
bool readQtNetD (const char *fileName)
void readAre (const char *fileName)
bool writeSol (const char *fileName, int K, const std::vector< unsigned char > &part) const
bool readHMetisSol (const char *fileName, std::vector< unsigned char > &part) const
bool hasFixedCells ()
bool checkOk () const
void printNetDist () const
int getCostModel () const
void setCostModel (int costModel)
unsigned int cutCost (const std::vector< unsigned char > &part, unsigned int numOfPartitions) const
unsigned int KMinus1Cost (const std::vector< unsigned char > &part, unsigned int numOfPartitions) const
unsigned int SOEDCost (const std::vector< unsigned char > &part, unsigned int numOfPartitions) const
unsigned int HyperEdgeCost (const std::vector< unsigned char > &part) const
template<class MetricFunction >
unsigned int cutCost (const vector< unsigned char > &part, MetricFunction metric, unsigned int numOfPartitions) const
Static Protected Member Functions
static void connect (Pin &p, Cell &v, Net &e)
Protected Attributes
unsigned int _numCells
unsigned int _numNets
unsigned int _numPins
unsigned int _padOffset
unsigned int _maxDegree
std::vector< Cell > _cellList
std::vector< Net > _netList
std::vector< Pin > _pinList
unsigned int _totalWeight
int _hasFixedCells
int _costModel
Detailed Description
A netlist base class. This class owns its cells, nets and pins.
Constructor & Destructor Documentation
NetlistBase::NetlistBase ()
Constructor
NetlistBase::~NetlistBase ()
Destructor
References clear().
Member Function Documentation
bool NetlistBase::checkOk () const
Check if the netlist was created properly. Take O(n+m) time.
References Node::firstAdjPin(), Pin::getCell(), getCell(), Pin::getNet(), getNet(), PinForNetCursorTmpl< Net_, Pin_ >::getNext(), PinForCellCursorTmpl< Cell_, Pin_ >::getNext(), getNumCells(), getNumNets(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), and PinForCellCursorTmpl< Cell_, Pin_ >::hasNext().
Referenced by readHMetis(), readNetD(), and NetlistBaseTestCase::testCreate().
void NetlistBase::clear ()
Reset an empty netlist
Reset to an empty NetlistBase
Reimplemented in Netlist.
References _cellList, _costModel, _maxDegree, _netList, _numCells, _numNets, _numPins, _pinList, and _totalWeight.
Referenced by ~NetlistBase().
void NetlistBase::clrFixedAllNets () [inline]
Clear visited attribute of all nets. Take O(m) time.
References Net::clrFixed(), getNet(), and getNumNets().
Referenced by NetlistTestCase::testContraction().
void NetlistBase::clrVisitedAllCells () const [inline]
Clear visited attribute of all cells. Take O(n) time.
References Cell::clrVisited(), getCell(), and getNumCells().
Referenced by LayerAssignmentServ::doAssignment(), CycleRemovalServ::selectIndependentNets(), and Netlist::setProxCells().
void NetlistBase::clrVisitedAllNets () const [inline]
Clear visited attribute of all nets. Take O(n) time.
References Net::clrVisited(), getNet(), and getNumNets().
Referenced by Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), CycleRemovalServ::selectIndependentNets(), and Netlist::setProxCells().
static void NetlistBase::connect (Pin & p, Cell & v, Net & e) [inline, static, protected]
Connect cell v to net e by mean of p
Referenced by readHMetis(), and readNetD().
unsigned int NetlistBase::cutCost (const std::vector< unsigned char > & part, unsigned int numOfPartitions) const
Returns:
the cut cost according to the defined cost model. Take O(m) time.
Referenced by KMinus1Cost(), QPartApp::slotPartRun(), and SOEDCost().
template<class MetricFunction > unsigned int NetlistBase::cutCost (const vector< unsigned char > & part, MetricFunction metric, unsigned int numOfPartitions) const [inline]
Returns:
the cut cost of partition according to the metric.
References PinForNetCursorTmpl< Net_, Pin_ >::count(), getCell(), getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), getNumNets(), Net::getWeight(), and PinForNetCursorTmpl< Net_, Pin_ >::hasNext().
Cell& NetlistBase::getCell (unsigned int id) [inline]
Returns:
cell by index. Precondition: index within array bound.
References _cellList.
Referenced by checkOk(), clrVisitedAllCells(), cutCost(), LayerAssignmentServ::doAssignment(), getId(), CycleRemovalServ::handleNextBest(), CycleRemovalServ::handleSink(), CycleRemovalServ::handleSrc(), hasFixedCells(), HyperEdgeCost(), Netlist::initWeightList(), Netlist::isVILEOk(), Netlist::maximumIndependentSetOK(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), Netlist::minimumNetCoverOK(), Netlist::projectDown(), Netlist::projectUp(), CycleRemovalServ::selectIndependentNets(), Netlist::setFixedNets(), Netlist::setProxCells(), CycleRemovalServ::setup(), NetlistBaseTestCase::testCell(), NetlistBaseTestCase::testNetCursor(), LayerAssignmentServ::writeDot(), and writeHMetis().
const Cell& NetlistBase::getCell (unsigned int id) const [inline]
Returns:
cell by index. Precondition: index with array bound.
References _cellList.
int NetlistBase::getCostModel () const [inline]
Returns:
the cost model.
References _costModel.
Referenced by Netlist::contractPhase2().
unsigned int NetlistBase::getId (const Net & e) const [inline]
Returns:
net index.
References getNet().
unsigned int NetlistBase::getId (const Cell & c) const [inline]
Returns:
cell index.
References getCell().
Referenced by NetlistBaseTestCase::testCell(), NetlistBaseTestCase::testNet(), and LayerAssignmentServ::writeDot().
unsigned int NetlistBase::getMaxDegree () const [inline]
Returns:
the max number of pins on one cell
References _maxDegree.
Referenced by CycleRemovalServ::CycleRemovalServ(), Netlist::firstChoice(), FMBiGainMgr::FMBiGainMgr(), FMBiGainMgr2::FMBiGainMgr2(), FMKWayGainMgr2::FMKWayGainMgr2(), FMKWayGainMgr4::FMKWayGainMgr4(), FMPartMgrBase::FMPartMgrBase(), and NetlistBaseTestCase::testCreate().
Net& NetlistBase::getNet (unsigned int id) [inline]
Returns:
net by index. Precondition: index with array bound.
References _netList.
Referenced by checkOk(), clrFixedAllNets(), clrVisitedAllNets(), Netlist::clusterSize(), cutCost(), LayerAssignmentServ::doAssignment(), Netlist::firstChoice(), getId(), HyperEdgeCost(), Netlist::markHighFanOutNets(), Netlist::markZeroPinNets(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), printNetDist(), CycleRemovalServ::selectIndependentNets(), Netlist::setFixedNets(), CycleRemovalServ::setup(), NetlistBaseTestCase::testCellCursor(), NetlistBaseTestCase::testNet(), NetlistBaseTestCase::testPinCursor(), and writeDot().
const Net& NetlistBase::getNet (unsigned int id) const [inline]
Returns:
the net by index. Precondition: index with array bound.
References _netList.
unsigned int NetlistBase::getNumCells () const [inline]
Returns:
the number of cells
References _numCells.
Referenced by checkOk(), clrVisitedAllCells(), Netlist::contractCore(), CycleRemovalServ::CycleRemovalServ(), LayerAssignmentServ::doAssignment(), CycleRemovalServ::doRemove(), FMKWayGainMgr2::FMKWayGainMgr2(), FMKWayGainMgr4::FMKWayGainMgr4(), hasFixedCells(), Netlist::initWeightList(), LayerAssignmentServ::LayerAssignmentServ(), Netlist::maximumIndependentSetOK(), Netlist::minimumNetCover2(), Netlist::minimumNetCoverOK(), Netlist::projectDown(), Netlist::projectUp(), Netlist::setProxCells(), CycleRemovalServ::setup(), QPartApp::slotPartRun(), NetlistBaseTestCase::testCreate(), NetlistBaseTestCase::testCutCost(), NetlistTestCase::testProjection(), CycleRemovalServ::verifyOK(), LayerAssignmentServ::writeDot(), and writeSol().
unsigned int NetlistBase::getNumNets () const [inline]
Returns:
the number of nets
References _numNets.
Referenced by checkOk(), clrFixedAllNets(), clrVisitedAllNets(), Netlist::clusterSize(), Netlist::contractCore(), cutCost(), CycleRemovalServ::CycleRemovalServ(), LayerAssignmentServ::doAssignment(), Netlist::firstChoice(), HyperEdgeCost(), LayerAssignmentServ::LayerAssignmentServ(), Netlist::markHighFanOutNets(), Netlist::markZeroPinNets(), Netlist::maximumIndependentSet(), printNetDist(), CycleRemovalServ::selectIndependentNets(), Netlist::setFixedNets(), CycleRemovalServ::setup(), NetlistBaseTestCase::testCreate(), NetlistTestCase::testMIS(), NetlistTestCase::testMNC(), and LayerAssignmentServ::writeDot().
unsigned int NetlistBase::getNumPads () const [inline]
Returns:
the number of pads. Note: only for netlists contructed by IBM .NET format.
References _numCells, and _padOffset.
Referenced by NetlistBaseTestCase::testCreate(), and LayerAssignmentServ::writeDot().
unsigned int NetlistBase::getNumPins () const [inline]
Returns:
the number of pins
References _numPins.
Referenced by PathMgr::PathMgr(), and NetlistBaseTestCase::testCreate().
Pin& NetlistBase::getPin (unsigned int id) [inline]
Returns:
pin by index. Precondition: index with array bound.
References _pinList.
Referenced by PathMgr::PathMgr().
const Pin& NetlistBase::getPin (unsigned int id) const [inline]
Returns:
the pin by index. Precondition: index with array bound.
References _pinList.
unsigned int NetlistBase::getTotalWeight () const [inline]
Returns:
total weight of cells.
References _totalWeight.
Referenced by Netlist::contractPhase2(), Netlist::isVILEOk(), and NetlistBaseTestCase::testCreate().
bool NetlistBase::hasFixedCells ()
Returns:
true if the netlist contains fixed cells. Take O(n) time the first time it is called.
References getCell(), getNumCells(), and Cell::isFixed().
Referenced by NetlistBaseTestCase::testCreate().
unsigned int NetlistBase::HyperEdgeCost (const std::vector< unsigned char > & part) const
Returns:
the cut cost in Hyperedge metric. This is the number of the hyperedges that span multiple partition. Take O(m) time.
References getCell(), getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), getNumNets(), Net::getWeight(), and PinForNetCursorTmpl< Net_, Pin_ >::hasNext().
Referenced by NetlistBaseTestCase::testCutCost().
unsigned int NetlistBase::KMinus1Cost (const std::vector< unsigned char > & part, unsigned int numOfPartitions) const
Returns:
the cut cost in the (K-1) metric. The partitioning routines in this package try to minimize this quantity. Take O(m) time.
the cut cost of partition in K-1 metric.
References cutCost().
Referenced by NetlistBaseTestCase::testCutCost().
void NetlistBase::printNetDist () const
Print the net distribution information
References PinForNetCursorTmpl< Net_, Pin_ >::count(), getNet(), and getNumNets().
void NetlistBase::readAre (const char * fileName)
Read the .are format
References _cellList, _numCells, _padOffset, _totalWeight, and Cell::setWeight().
bool NetlistBase::readHMetis (const char * hgrFileName)
Read the HMetis format.
References _cellList, _maxDegree, _netList, _numCells, _numNets, _numPins, _padOffset, _pinList, _totalWeight, checkOk(), connect(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), Net::getWeight(), and PinForCellCursorTmpl< Cell_, Pin_ >::hasNext().
bool NetlistBase::readHMetisSol (const char * fileName, std::vector< unsigned char > & part) const
Read the partition solution in hmetis format.
References _numCells.
bool NetlistBase::readNetD (const char * fileName)
Read the .netD format
References _cellList, _maxDegree, _netList, _numCells, _numNets, _numPins, _padOffset, _pinList, _totalWeight, checkOk(), and connect().
bool NetlistBase::readQtNetD (const char * fileName)
Read the .netD format
void NetlistBase::setCostModel (int costModel) [inline]
Set the cost model.
References _costModel.
Referenced by FMKWayPartMgrBase::FMKWayPartMgrBase().
unsigned int NetlistBase::SOEDCost (const std::vector< unsigned char > & part, unsigned int numOfPartitions) const
Returns:
the cut cost in Sum-Of-External-Degrees (SOED) metric. The external degree of a partition is defined as the number of hyperedges, that are incident but not fully inside the partition. Take O(m) time.
the cut cost of partitions in Sum-Of-External-Degrees (SOED) metric. Note that the SOED cost is equal to the K-1 cost plus the HyperEdge cost.
References cutCost().
Referenced by NetlistBaseTestCase::testCutCost().
int NetlistBase::writeDot (const char * fileName) const
Write the Dot format.
References _cellList, _numCells, _numNets, _padOffset, Pin::getNet(), getNet(), PinForCellCursorTmpl< Cell_, Pin_ >::getNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), and Cell::isPad().
int NetlistBase::writeHMetis (const char * fileName) const
Write the HMetis format.
References _cellList, _netList, _numCells, _numNets, getCell(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), and PinForNetCursorTmpl< Net_, Pin_ >::hasNext().
bool NetlistBase::writeSol (const char * fileName, int K, const std::vector< unsigned char > & part) const
Write the partition solution.
References _cellList, _padOffset, getNumCells(), and Cell::isPad().
Member Data Documentation
std::vector<Cell> NetlistBase::_cellList [protected]
array of all cells
Referenced by clear(), Netlist::contractCore(), getCell(), readAre(), readHMetis(), readNetD(), writeDot(), writeHMetis(), and writeSol().
int NetlistBase::_costModel [protected]
Cost Model: 0: HyperEdge, 1: K-1 metric, 2: SOED
Referenced by clear(), getCostModel(), and setCostModel().
unsigned int NetlistBase::_maxDegree [protected]
maximum pins of cells
Referenced by clear(), getMaxDegree(), readHMetis(), and readNetD().
std::vector<Net> NetlistBase::_netList [protected]
array of all nets
Referenced by clear(), Netlist::contractCore(), getNet(), readHMetis(), readNetD(), and writeHMetis().
unsigned int NetlistBase::_numCells [protected]
number of cells
Referenced by clear(), Netlist::contractCore(), getNumCells(), getNumPads(), Netlist::initVertexArray(), readAre(), readHMetis(), readHMetisSol(), readNetD(), writeDot(), and writeHMetis().
unsigned int NetlistBase::_numNets [protected]
number of nets
Referenced by clear(), Netlist::contractCore(), getNumNets(), readHMetis(), readNetD(), writeDot(), and writeHMetis().
unsigned int NetlistBase::_numPins [protected]
number of pins
Referenced by clear(), getNumPins(), readHMetis(), and readNetD().
unsigned int NetlistBase::_padOffset [protected]
pad is one kind of cells
Referenced by getNumPads(), readAre(), readHMetis(), readNetD(), writeDot(), and writeSol().
std::vector<Pin> NetlistBase::_pinList [protected]
array of all pins
Referenced by clear(), getPin(), readHMetis(), and readNetD().
unsigned int NetlistBase::_totalWeight [protected]
total weight of cells
Referenced by clear(), getTotalWeight(), readAre(), readHMetis(), and readNetD().
The documentation for this class was generated from the following files:
NetlistBase.hpp
FMBiPartMgrBase.cpp
FMKWayPartMgrBase.cpp
NetlistBase.cpp