FMBiPartComm Class Reference
FMBiPartComm Class Reference
Bi-partitioner Core Engine
#include <FMBiPartComm.hpp>
Public Member Functions
template<class GainStruct >
void updateMove2PinNet (const Net &e, const vector< unsigned char > &part, unsigned int fromPart, const Cell &v, GainStruct &ms)
template<class GainStruct >
void updateMoveGeneralNet (const Net &e, const vector< unsigned char > &part, unsigned int fromPart, const Cell &v, GainStruct &ms)
Protected Member Functions
FMBiPartComm (const FMParam &param)
virtual ~FMBiPartComm ()
void initGain (const Net &e, const std::vector< unsigned char > &part)
template<class GainStruct >
void updateMove2PinNet (const Net &e, const std::vector< unsigned char > &part, unsigned int fromPart, const Cell &v, GainStruct &s)
template<class GainStruct >
void updateMoveGeneralNet (const Net &e, const std::vector< unsigned char > &part, unsigned int fromPart, const Cell &v, GainStruct &s)
int getGain (const FMMoveInfo &moveInfo) const
Protected Attributes
std::vector< short > _gain
int _num [2]
Detailed Description
FM Bi-Partitioning Manager Common Utility. This class is shared by FM bi-partitioning manager and refinement bi-partitioning manager. Common code for calculating the gain.
Constructor & Destructor Documentation
FMBiPartComm::FMBiPartComm (const FMParam & param) [protected]
Constructor
References FMPartMgrBase::getNetlist(), and Netlist::initVertexArray().
virtual FMBiPartComm::~FMBiPartComm () [inline, protected, virtual]
Constructor
Member Function Documentation
int FMBiPartComm::getGain (const FMMoveInfo & moveInfo) const [inline, protected]
Returns:
the gain of the moving cell.
References _gain, and FMMoveInfo::_i_v.
void FMBiPartComm::initGain (const Net & e, const std::vector< unsigned char > & part) [protected]
Setup the initial gain.
Initialize the gain structure (c.f. Sarrafzadeh and Wong, page 38)
References FMPartMgrBase::_cellList, _gain, _num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), Net::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), and Cell::isVisited().
Referenced by FMKWayPartCore4::initGainCore().
template<class GainStruct > void FMBiPartComm::updateMove2PinNet (const Net & e, const vector< unsigned char > & part, unsigned int fromPart, const Cell & v, GainStruct & ms)
When the cell v is moved from fromPart, update the gains and the gain structures of its neighbors. (c.f. Sarrafzadeh and Wong, page 39)
Parameters:
e net connected to the moved cell
part current partition solution
fromPart from where v moves
v the moving cell
ms gain related structre
References FMPartMgrBase::_cellList, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), and Net::getWeight().
template<class GainStruct > void FMBiPartComm::updateMove2PinNet (const Net & e, const std::vector< unsigned char > & part, unsigned int fromPart, const Cell & v, GainStruct & s) [protected]
Update the gain structure given the moving vertex
Referenced by FMBiPartCore4::updateMove(), and FMBiPartCore::updateMove().
template<class GainStruct > void FMBiPartComm::updateMoveGeneralNet (const Net & e, const std::vector< unsigned char > & part, unsigned int fromPart, const Cell & v, GainStruct & s) [protected]
Update the gain structure given the moving vertex
Referenced by FMBiPartCore4::updateMove(), and FMBiPartCore::updateMove().
template<class GainStruct > void FMBiPartComm::updateMoveGeneralNet (const Net & e, const vector< unsigned char > & part, unsigned int fromPart, const Cell & v, GainStruct & ms)
When the cell v is moved from fromPart, update the gains and the gain structures of its neighbors. (c.f. Sarrafzadeh and Wong, page 39)
Parameters:
e net connected to the moved cell
part current partition solution
fromPart from where v moves
v the moving cell
ms gain related structre
References FMPartMgrBase::_cellList, _num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), Net::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), and Cell::isVisited().
Member Data Documentation
std::vector<short> FMBiPartComm::_gain [protected]
cache neighbor information gain of each node
Referenced by getGain(), initGain(), FMKWayPartCore4::initGainCore(), FMBiPartCore4::pushBack4(), and FMBiPartCore4::updateMove4().
int FMBiPartComm::_num[2] [protected]
number of vertices on each partitions
Referenced by initGain(), FMBiPartCore4::updateMove(), FMBiPartCore::updateMove(), and updateMoveGeneralNet().
The documentation for this class was generated from the following files:
FMBiPartComm.hpp
FMBiPartComm.cpp