FMBiGainMgr2 Class Reference
FMBiGainMgr2 Class Reference
Bi-partitioner Core Engine
#include <FMBiGainMgr2.hpp>
Public Member Functions
FMBiGainMgr2 (const FMParam &param)
void init (const std::vector< unsigned char > &part, const std::vector< short > &gain)
Vertex * select (FMMoveInfo &moveInfo, const std::vector< unsigned char > &, const BiConstrMgr3 &constraintMgr)
Vertex * select (FMMoveInfo &moveInfo, const BiConstrMgr3 &constraintMgr)
int getGain (const FMMoveInfo &moveInfo) const
void updateMove (const FMMoveInfo &moveInfo)
void updateNeighbor (unsigned int whichPart, unsigned int i_w, short deltaGain)
void pushBack (unsigned int whichPart, const Cell &v, short gain)
void updateGain (const std::vector< unsigned char > &part, const std::vector< short > &gain)
Protected Attributes
Netlist & _H
VertexPQ _gainBucket [2]
VertexPQCur _gainBucketCur [2]
Vertex *const _vertexArray
Cell *const _cellList
Detailed Description
FM Bi-partitioning Gain Manager. This class responsible for maintaining the gain bucket structures and helps to select the best vertex. The data structure used for selecting the next vertex to be moved is as follows. The vertex gain is an (short) integer and each vertex has its gain in the range -pmax to +pmax, where pmax is the maximum vertex degree in the hypergraph. Since vertex gain have restricted values, 'bucket' sorting can be used to maintain a sorted list of vertex gains. This is done using an array BUCKET[-pmax, ..., pmax], whose kth entry contains a doubly-linked list of free vertices with gains currently equal to k (GBPQueue). Two such arrays are used, one for each partition. Each array is maintained by moving a vertex to the appropriate bucket whenever its gain changes due to the movement of one of its neighbors. Direct access to each vertex, from a separate field in the VERTEX array (_vertexArray), allows removal of a vertex from its current list and its movement to the head of its new bucket list in constant time. As only free vertices are allowed to move, therefore, only their gains are updated. For each BUCKET array, a _max index is maintained which is used to keep track of the bucket having a vertex of highest gain. This index is updated by decrementing it whenever its bucket is found to be empty and reseetting it to a higher bucket whenever a vertex moves to a bucket above _max. Experimental results on real circuits have shown that gains tend to cluster sharply around the origin and that _max moves very little, making the implementation exceptionally fast and simple. Reference: N. Sherwani. Algorithms for VLSI Physical Desgin Automation, 3rd Ed.
Constructor & Destructor Documentation
FMBiGainMgr2::FMBiGainMgr2 (const FMParam & param)
Constructor
References _gainBucket, _gainBucketCur, _H, GBPQueueCursor< BPQNode >::associate(), NetlistBase::getMaxDegree(), and GBPQueue< BPQNode >::setUp().
Member Function Documentation
int FMBiGainMgr2::getGain (const FMMoveInfo & moveInfo) const [inline]
Returns:
the gain of vertex if it moves
References FMMoveInfo::_fromPart, _gainBucket, FMMoveInfo::_i_v, _vertexArray, and GBPQueue< BPQNode >::getKey().
void FMBiGainMgr2::init (const std::vector< unsigned char > & part, const std::vector< short > & gain)
Setup the gain bucket structure
Referenced by updateGain().
void FMBiGainMgr2::pushBack (unsigned int whichPart, const Cell & v, short gain) [inline]
Push back the cell to gain bucket. Precondition: v is not in bucket.
References _cellList, _gainBucket, _vertexArray, and GBPQueue< BPQNode >::pushBack().
Vertex* FMBiGainMgr2::select (FMMoveInfo & moveInfo, const std::vector< unsigned char > & , const BiConstrMgr3 & constraintMgr) [inline]
Select the next "best" vertex that satisfies all constraints when it is moved. In this implementation, we pick two vertices from both partitions with the highest gains. If both has equal gain, the one that minimizes the balance different will be chosen.
Vertex * FMBiGainMgr2::select (FMMoveInfo & moveInfo, const BiConstrMgr3 & constraintMgr)
Returns:
the next "best" vertex that satisfies all constraints when it is moved. Return also move from where to where.
References _cellList, _gainBucketCur, _vertexArray, GBPQueueCursor< BPQNode >::getNext(), GBPQueueCursor< BPQNode >::getRelKey(), GBPQueueCursor< BPQNode >::reset(), and BiConstrMgr3::satisfied().
void FMBiGainMgr2::updateGain (const std::vector< unsigned char > & part, const std::vector< short > & gain) [inline]
Update the gain structure according to the freeVertexList.
References init().
void FMBiGainMgr2::updateMove (const FMMoveInfo & moveInfo) [inline]
Update the moved cell in the gain bucket
References FMMoveInfo::_fromPart, _gainBucket, FMMoveInfo::_i_v, _vertexArray, and GBPQueue< BPQNode >::detach().
void FMBiGainMgr2::updateNeighbor (unsigned int whichPart, unsigned int i_w, short deltaGain) [inline]
Update the neighbor of the moved cells due to the move.
Reimplemented in FMBiGainMgr3.
References _cellList, _gainBucket, _vertexArray, and GBPQueue< BPQNode >::modifyKeyLIFOBy().
Member Data Documentation
Cell* const FMBiGainMgr2::_cellList [protected]
Cell array offset
Referenced by pushBack(), select(), FMBiGainMgr3::updateNeighbor(), and updateNeighbor().
VertexPQ FMBiGainMgr2::_gainBucket[2] [protected]
two gain buckets
Referenced by FMBiGainMgr2(), getGain(), pushBack(), updateMove(), FMBiGainMgr3::updateNeighbor(), and updateNeighbor().
VertexPQCur FMBiGainMgr2::_gainBucketCur[2] [protected]
gain bucket cursor
Referenced by FMBiGainMgr2(), and select().
Netlist& FMBiGainMgr2::_H [protected]
the hypergraph
Referenced by FMBiGainMgr2().
Vertex* const FMBiGainMgr2::_vertexArray [protected]
VERTEX array
Referenced by getGain(), pushBack(), select(), updateMove(), FMBiGainMgr3::updateNeighbor(), and updateNeighbor().
The documentation for this class was generated from the following files:
FMBiGainMgr2.hpp
FMBiGainMgr2.cpp