FMLimits Class Reference
FMLimits Class Reference
Partitioning Group.
#include <FMLimits.hpp>
Static Public Member Functions
static unsigned int maxNumOfPartitions ()
static int maxCellWeight ()
static int maxNetWeight ()
static unsigned int maxDegreeOfCells ()
static unsigned int maxFanOutOfNets ()
Detailed Description
Limitations of the Software. Most of the limitations are due to the decision of trade-off either the memory storge or run-time or both. If larger capabilities are requested, do let me know. Thanks. By the way, another limitation of this software is that in fact it is not thread-safe. One reason is that I don't know how to write thread-safe codes. Second, I tried to replace the current STL with the STLport's thread-safe STL and found that the run-time almost double than before. Because so far this software is only used for a stand-alone non-window program, this issue leaves as a future enhancement.
Member Function Documentation
static int FMLimits::maxCellWeight () [inline, static]
Returns:
maximum cell weight.
See also:
Cell.
Referenced by Cell::setWeight().
static unsigned int FMLimits::maxDegreeOfCells () [inline, static]
Returns:
maximum (weighted) degree of cells. Note that for SOED cost model (Sum-Of-External-Degrees), the limit should be further divided by 2 in order to guarantee no risk.
Referenced by FMPartMgrBase::FMPartMgrBase().
static unsigned int FMLimits::maxFanOutOfNets () [inline, static]
Returns:
maximum number of pins per net. Note that the partitioner can tolerate the present of high-fanout net by pruning them out before start. But it may degrade the quality of results if a circuit contains a lot of such nets.
Referenced by Net::isHighFanout().
static int FMLimits::maxNetWeight () [inline, static]
Returns:
maximum net weight.
See also:
Net
Referenced by Net::setWeight().
static unsigned int FMLimits::maxNumOfPartitions () [inline, static]
Returns:
maximum number of partitions
The documentation for this class was generated from the following file:
FMLimits.hpp