GStackCursor< SNode > Class Template Reference
GStackCursor< SNode > Class Template Reference
Data Structure Group
#include <GStack.hpp>
Public Member Functions
GStackCursor ()
GStackCursor (GStack< SNode > &S)
void associate (GStack< SNode > &S)
bool hasNext () const
void reset ()
SNode * getNext ()
Detailed Description
template<class SNode>
class GStackCursor< SNode >
Stack Cursor. Traverse the stack from the first item. Usually it is safe to push stack items during the cursor is active, assuming that the detached items are not used in other places or are not deallocated.
Constructor & Destructor Documentation
template<class SNode> GStackCursor< SNode >::GStackCursor () [inline]
Constructor
template<class SNode> GStackCursor< SNode >::GStackCursor (GStack< SNode > & S) [inline]
Constructor
References GStackCursor< SNode >::reset().
Member Function Documentation
template<class SNode> void GStackCursor< SNode >::associate (GStack< SNode > & S) [inline]
Associate to the stack S and reset the cursor.
References GStackCursor< SNode >::reset().
template<class SNode> SNode* GStackCursor< SNode >::getNext () [inline]
Returns:
the next item. Precondition: next item exist.
References GStackCursor< SNode >::hasNext().
template<class SNode> bool GStackCursor< SNode >::hasNext () const [inline]
Returns:
true if there is a next item.
Referenced by GStackCursor< SNode >::getNext().
template<class SNode> void GStackCursor< SNode >::reset () [inline]
Reset the cursor to the first position.
Referenced by GStackCursor< SNode >::associate(), and GStackCursor< SNode >::GStackCursor().
The documentation for this class was generated from the following file:
GStack.hpp