Net Class Reference
Net Class Reference
Data Modeling Group.
#include <Net.hpp>
Public Member Functions
Net ()
bool isFixed () const
void setFixed ()
void clrFixed ()
void toggleFixed ()
bool isVisited () const
void setVisited () const
void clrVisited () const
void toggleVisited ()
int getWeight () const
void setWeight (int weight)
bool isHighFanout () const
Friends
class Netlist
class NetlistBase
Detailed Description
A net class. Net is represented by hyperedge. In some other implementations, net is first approximated by using the clique model. If a circuit contains mostly two-pin nets, this strategy may greatly simplifies algorithms while it doesn't affect the result too much.
Constructor & Destructor Documentation
Net::Net () [inline]
Construtor
Member Function Documentation
void Net::clrFixed () [inline]
Clear fixed.
Referenced by NetlistBase::clrFixedAllNets(), Netlist::markHighFanOutNets(), and Netlist::setFixedNets().
void Net::clrVisited () const [inline]
Clear visited.
Referenced by NetlistBase::clrVisitedAllNets(), Netlist::firstChoice(), Netlist::maximumIndependentSet(), and CycleRemovalServ::selectIndependentNets().
int Net::getWeight () const [inline]
Returns:
node weight.
Referenced by NetlistBase::cutCost(), NetlistBase::HyperEdgeCost(), FMBiPartComm::initGain(), FMKWayPartComm::initGainHEdge(), FMKWayPartComm::initGainKMinus1(), FMKWayPartComm::initGainSOED(), NetlistBase::readHMetis(), NetlistBaseTestCase::testNet(), FMBiPartComm::updateMove2PinNet(), FMBiPartComm::updateMoveGeneralNet(), FMKWayPartComm::updateMoveGeneralNetCommKMinus1(), FMKWayPartComm::updateMoveGeneralNetHEdge4(), FMKWayPartComm::updateMoveGeneralNetKMinus14(), FMKWayPartComm::updateMoveGeneralNetSOED4(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore4::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore4::updateMoveSOED(), FMKWayPartCore::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
bool Net::isFixed () const [inline]
Returns:
true if node is fixed
Referenced by Netlist::clusterSize(), Netlist::firstChoice(), Netlist::markZeroPinNets(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), and Netlist::minimumNetCover2().
bool Net::isHighFanout () const [inline]
Returns:
true if this is a high fanout net
References Node::firstAdjPin(), and FMLimits::maxFanOutOfNets().
Referenced by FMKWayPartCore4::initGainCore(), Netlist::markHighFanOutNets(), FMBiPartCore4::updateMove(), FMBiPartCore::updateMove(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore4::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore4::updateMoveSOED(), FMKWayPartCore::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
bool Net::isVisited () const [inline]
Returns:
true if node is visited
Referenced by Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), CycleRemovalServ::selectIndependentNets(), and NetlistBaseTestCase::testNet().
void Net::setFixed () [inline]
Set fixed.
Referenced by Netlist::markHighFanOutNets(), Netlist::markZeroPinNets(), and Netlist::setFixedNets().
void Net::setVisited () const [inline]
Set visited.
Referenced by Netlist::firstChoice(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), and CycleRemovalServ::selectIndependentNets().
void Net::setWeight (int weight) [inline]
Set node weight. Precondition: weight non-negative (>= 0)
References FMLimits::maxNetWeight().
void Net::toggleFixed () [inline]
Toggle fixed.
void Net::toggleVisited () [inline]
Toggle visited.
The documentation for this class was generated from the following file:
Net.hpp