Pin Class Reference
Pin Class Reference
Data Modeling Group.
#include <Pin.hpp>
Public Types
enum DIRECTION { UNKNOWN, INPUT, OUTPUT, BIDIR }
Public Member Functions
Pin ()
DIRECTION getDirection () const
void setDirection (DIRECTION)
Cell & getCell () const
Net & getNet () const
Pin * nextAdjPinForCell () const
Friends
class Netlist
class NetlistBase
class Cell
class Net
Detailed Description
A Pin class. It may not be necessary to create pin in FM algorithm. However, we use this class for CycleRemoval algorithm.
Member Enumeration Documentation
enum Pin::DIRECTION
Pin direction enum.
Enumerator:
UNKNOWN
unknown direction
INPUT
input pin
OUTPUT
output pin
BIDIR
bi-direction pin
Constructor & Destructor Documentation
Pin::Pin () [inline]
A constructor.
Member Function Documentation
Cell& Pin::getCell () const [inline]
Returns:
the Cell connected to this pin
Referenced by NetlistBase::checkOk(), LayerAssignmentServ::doAssignment(), and Netlist::projectUp().
DIRECTION Pin::getDirection () const [inline]
Returns:
the direction (not support yet)
References UNKNOWN.
Referenced by LayerAssignmentServ::doAssignment(), CycleRemovalServ::handleNextBest(), PathMgr::PathMgr(), CycleRemovalServ::setup(), and LayerAssignmentServ::writeDot().
Net& Pin::getNet () const [inline]
Returns:
the net connected to this pin
Referenced by NetlistBase::checkOk(), LayerAssignmentServ::doAssignment(), CycleRemovalServ::handleNextBest(), Netlist::projectUp(), NetlistBase::writeDot(), and LayerAssignmentServ::writeDot().
Pin* Pin::nextAdjPinForCell () const [inline]
Returns:
the next adjacency pin (for cell)
void Pin::setDirection (DIRECTION) [inline]
Set the direction. (not support yet)
The documentation for this class was generated from the following file:
Pin.hpp