FMPartMgrBase Class Reference
FMPartMgrBase Class Reference
Partitioning Group.
#include <FMPartMgrBase.hpp>
Public Member Functions
virtual ~FMPartMgrBase ()
void setPValue (unsigned int pvalue)
void setQValue (unsigned int qvalue)
virtual unsigned int cutCost (const std::vector< unsigned char > &part) const =0
virtual unsigned int doPartitionOne (std::vector< unsigned char > &)=0
double doPartition (std::vector< unsigned char > &part, unsigned int starts=1)
int doPartitionQt (std::vector< unsigned char > &part, unsigned int starts=1)
int getBoundType () const
void setBoundType (int boundType)
double getBalanceTol () const
void setBalanceTol (double balTol)
int getUpperBound () const
int getLowerBound () const
void setUpperBound (int upperBound)
void setLowerBound (int lowerBound)
int getMaxDiff () const
unsigned int getInitCost () const
unsigned int getBestCost () const
double getAvgCost () const
double diff () const
bool isNoInit () const
void setNoInit (unsigned int cost)
int getVerbosity () const
void setVerbosity (int verbosity)
const FMParam & getParam () const
void noNeedSetHighFanoutNets ()
void noNeedSetFixedCells ()
void setAllowIllegal (bool allowIllegal)
bool allowIllegal () const
Protected Member Functions
FMPartMgrBase (const FMParam &param)
Netlist & getNetlist ()
const Netlist & getNetlist () const
void initNetlist ()
virtual void initBase ()
void setMaxDiff (int maxdiff)
unsigned int getNumCells () const
unsigned int getNumNets () const
unsigned int getTotalWeight () const
Protected Attributes
bool _noInit
unsigned int _initCost
Cell *const _cellList
Net *const _netList
bool _needSetHighFanoutNets
bool _needSetFixedCells
unsigned int _pvalue
unsigned int _qvalue
bool _allowIllegal
Detailed Description
FM Partitioning Manager Utility Base Class. Provide service such that calculate cut cost, constraint checking etc. This class is for all bi-partitoning and multi-way partitioning managers.
Constructor & Destructor Documentation
virtual FMPartMgrBase::~FMPartMgrBase () [inline, virtual]
Destructor
FMPartMgrBase::FMPartMgrBase (const FMParam & param) [protected]
Constructor
References FMException::FM_EXCEED_MAX_DEGREE, NetlistBase::getMaxDegree(), and FMLimits::maxDegreeOfCells().
Member Function Documentation
bool FMPartMgrBase::allowIllegal () const [inline]
Allow illegal solution
References _allowIllegal.
Referenced by setAllowIllegal().
virtual unsigned int FMPartMgrBase::cutCost (const std::vector< unsigned char > & part) const [pure virtual]
Returns:
the cut-cost
Implemented in FMBiPartMgrBase, and FMKWayPartMgrBase.
Referenced by doPartition(), and doPartitionQt().
double FMPartMgrBase::diff () const [inline]
Returns:
the difference btw two partitions in percentage of the total weight
References getTotalWeight().
double FMPartMgrBase::doPartition (std::vector< unsigned char > & part, unsigned int starts = 1)
Complete FM run.
Returns:
the elapsed time
Multiple run heuristic. Assume some randomness in initPart() and runFMOne().
References _initCost, _noInit, cutCost(), doPartitionOne(), and initBase().
virtual unsigned int FMPartMgrBase::doPartitionOne (std::vector< unsigned char > &) [pure virtual]
A single FM run.
Returns:
the cutcost.
Referenced by doPartition(), and doPartitionQt().
int FMPartMgrBase::doPartitionQt (std::vector< unsigned char > & part, unsigned int starts = 1)
Complete FM run in Qt.
Returns:
the elapsed time
References _initCost, _noInit, cutCost(), doPartitionOne(), and initBase().
double FMPartMgrBase::getAvgCost () const [inline]
Returns:
average cost. Note than if a circuit contains high fan-out nets that are skipped during the partition process, the value of this variable may not be accurate. In this case, use Netlist::cutCost() to get the accurate information. This variable is used in the multiple run and the multilevel method.
double FMPartMgrBase::getBalanceTol () const [inline]
Returns:
the balance tolerance.
Referenced by setBalanceTol().
unsigned int FMPartMgrBase::getBestCost () const [inline]
Returns:
best cost recorded. Note than if a circuit contains high fan-out nets that are skipped during the partition process, the value of this variable may not be accurate. In this case, use Netlist::cutCost() to get the accurate information. This variable is used in the multiple run and the multilevel method.
int FMPartMgrBase::getBoundType () const [inline]
Returns:
bound type
Referenced by setBalanceTol().
unsigned int FMPartMgrBase::getInitCost () const [inline]
Returns:
init cost
References _initCost.
int FMPartMgrBase::getLowerBound () const [inline]
Returns:
the allowed lower bound
int FMPartMgrBase::getMaxDiff () const [inline]
Returns:
maxdiff
Referenced by FMBiPartMgrBase::setDiff2().
Netlist& FMPartMgrBase::getNetlist () [inline, protected]
Returns:
netlist
Referenced by FMBiPartComm::FMBiPartComm(), FMKWayPartComm::FMKWayPartComm(), and FMKWayPartMgrBase::FMKWayPartMgrBase().
const Netlist& FMPartMgrBase::getNetlist () const [inline, protected]
Returns:
netlist
unsigned int FMPartMgrBase::getNumCells () const [inline, protected]
Returns:
the number of Cells
Referenced by FMKWayPartComm::FMKWayPartComm(), and FMKWayPartMgrBase::initPart().
unsigned int FMPartMgrBase::getNumNets () const [inline, protected]
Returns:
the number of Nets
Referenced by FMBiPartCore4::FMBiPartCore4(), FMKWayPartCore4::FMKWayPartCore4(), and FMKWayPartCore4::initGainCore().
const FMParam& FMPartMgrBase::getParam () const [inline]
Returns:
fixed parameters
unsigned int FMPartMgrBase::getTotalWeight () const [inline, protected]
Returns:
the total weight of cells
Referenced by diff(), and setBalanceTol().
int FMPartMgrBase::getUpperBound () const [inline]
Returns:
the allowed upper bound
int FMPartMgrBase::getVerbosity () const [inline]
Returns:
verbosity level, quiet(-1), normal(0), more messages(> 0)
virtual void FMPartMgrBase::initBase () [inline, protected, virtual]
Initialization before multiple runs
Reimplemented in FMBiPartMgrBase, and FMKWayPartMgrBase.
Referenced by doPartition(), and doPartitionQt().
bool FMPartMgrBase::isNoInit () const [inline]
Returns:
true if noInit mode is on
References _noInit.
void FMPartMgrBase::setAllowIllegal (bool allowIllegal) [inline]
Allow illegal solution
References _allowIllegal, and allowIllegal().
void FMPartMgrBase::setBalanceTol (double balTol)
Set the balance tolerance. Precondition: 0.0 < balTol < 1
References getBalanceTol(), getBoundType(), getTotalWeight(), setLowerBound(), and setUpperBound().
void FMPartMgrBase::setBoundType (int boundType) [inline]
Set bound type
void FMPartMgrBase::setLowerBound (int lowerBound) [inline]
Set the allowed lower bound
Referenced by setBalanceTol().
void FMPartMgrBase::setMaxDiff (int maxdiff) [inline, protected]
(For Multilevel code only) Set maxdiff
Referenced by FMBiPartMgrBase::setDiff2().
void FMPartMgrBase::setNoInit (unsigned int cost) [inline]
Do not initialize partition. In "noInit" mode, initial solution is supplied by the callers. This mode is useful for ECO (Engineering Change Order) flow. It is also used in the refinement phase of the multilevel method.
References _initCost, and _noInit.
void FMPartMgrBase::setUpperBound (int upperBound) [inline]
Set the allowed upper bound
Referenced by setBalanceTol().
void FMPartMgrBase::setVerbosity (int verbosity) [inline]
Set verbosity level, quiet(-1), normal(0), more messages(> 0)
Member Data Documentation
bool FMPartMgrBase::_allowIllegal [protected]
whether illegal sol'n is allowed
Referenced by allowIllegal(), and setAllowIllegal().
Cell* const FMPartMgrBase::_cellList [protected]
cell array offset
Referenced by FMBiPartComm::initGain(), FMKWayPartMgrBase::initPart(), FMKWayPartCore4::pushBack4(), FMBiPartCore4::pushBack4(), FMBiPartCore::updateMove(), FMKWayPartComm::updateMove2PinNet(), FMBiPartComm::updateMove2PinNet(), FMKWayPartComm::updateMove2PinNet4(), FMBiPartComm::updateMoveGeneralNet(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
unsigned int FMPartMgrBase::_initCost [protected]
init cost
Referenced by doPartition(), doPartitionQt(), getInitCost(), and setNoInit().
Net* const FMPartMgrBase::_netList [protected]
net array offset
Referenced by FMKWayPartCore4::initGainCore(), FMBiPartCore4::updateMove(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore4::updateMoveKMinus1(), and FMKWayPartCore4::updateMoveSOED().
bool FMPartMgrBase::_noInit [protected]
No internal init. false=default
Referenced by doPartition(), doPartitionQt(), isNoInit(), and setNoInit().
The documentation for this class was generated from the following files:
FMPartMgrBase.hpp
FMPartMgrBase.cpp
FMPartMgrExt.cpp