NetCursorTmpl< Net_, Cell_, Pin_ > Class Template Reference
NetCursorTmpl< Net_, Cell_, Pin_ > Class Template Reference
Data Modeling Group.
#include <NetlistBase.hpp>
Public Member Functions
NetCursorTmpl (Cell_ &n)
Net_ & getNext ()
Detailed Description
template<class Net_, class Cell_, class Pin_ = Pin>
class NetCursorTmpl< Net_, Cell_, Pin_ >
Cursor to traverse all the cells of one net. Since there is no direct pointer to the cells (need to go through pin). It may make the FM algorithm a little slower than the highly tuned implementation.
Constructor & Destructor Documentation
template<class Net_ , class Cell_ , class Pin_ = Pin> NetCursorTmpl< Net_, Cell_, Pin_ >::NetCursorTmpl (Cell_ & n) [inline]
Constructor
Member Function Documentation
template<class Net_ , class Cell_ , class Pin_ = Pin> Net_& NetCursorTmpl< Net_, Cell_, Pin_ >::getNext () [inline]
Returns:
the next cell. This function is crucial in FM algorithm. Precondition: there exist the next item.
Reimplemented from PinForCellCursorTmpl< Cell_, Pin_ >.
Referenced by CycleRemovalServ::handleSink(), CycleRemovalServ::handleSrc(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), NetlistBase::readHMetis(), CycleRemovalServ::selectIndependentNets(), NetlistBaseTestCase::testNetCursor(), FMBiPartCore4::updateMove(), FMBiPartCore::updateMove(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore4::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore4::updateMoveSOED(), FMKWayPartCore::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
The documentation for this class was generated from the following file:
NetlistBase.hpp