GDListConstCursor< DNode > Class Template Reference
GDListConstCursor< DNode > Class Template Reference
Data Structure Group
#include <GDList.hpp>
Public Member Functions
GDListConstCursor ()
GDListConstCursor (const GDList< DNode > &L)
void associate (const GDList< DNode > &L)
bool hasNext () const
void reset ()
const DNode & getNext ()
Detailed Description
template<class DNode>
class GDListConstCursor< DNode >
List Cursor. Traverse the list from the first item. Usually it is safe to attach/detach list items during the cursor is active.
Constructor & Destructor Documentation
template<class DNode> GDListConstCursor< DNode >::GDListConstCursor () [inline]
Default Constructor
template<class DNode> GDListConstCursor< DNode >::GDListConstCursor (const GDList< DNode > & L) [inline]
Constructor
Member Function Documentation
template<class DNode> void GDListConstCursor< DNode >::associate (const GDList< DNode > & L) [inline]
Associate to the list L and reset the cursor.
References GDListConstCursor< DNode >::reset().
template<class DNode> const DNode& GDListConstCursor< DNode >::getNext () [inline]
Returns:
the next item. Precondition: next item exist
References GDListConstCursor< DNode >::hasNext().
Referenced by GDListTestCase::testConstCursor().
template<class DNode> bool GDListConstCursor< DNode >::hasNext () const [inline]
Returns:
true if there is a next item.
Referenced by GDListConstCursor< DNode >::getNext(), and GDListTestCase::testConstCursor().
template<class DNode> void GDListConstCursor< DNode >::reset () [inline]
Reset the cursor to the first position.
Referenced by GDListConstCursor< DNode >::associate().
The documentation for this class was generated from the following file:
GDList.hpp