QPartApp Class Reference
QPartApp Class Reference
#include <qpart.h>
Public Slots
void slotFileNew ()
void slotFileOpen ()
void slotFileSave ()
void slotFileSaveAs ()
void slotFileClose ()
void slotFilePrint ()
void slotFileQuit ()
void slotEditCut ()
void slotEditCopy ()
void slotEditPaste ()
void slotPartConstraints ()
void slotPartRun ()
void slotViewToolBar (bool toggle)
void slotViewStatusBar (bool toggle)
void slotHelpAbout ()
Public Member Functions
QPartApp ()
~QPartApp ()
void initActions ()
void initMenuBar ()
void initToolBar ()
void initStatusBar ()
void initDoc ()
void initView ()
bool queryExit ()
Detailed Description
This Class is the base class for your application. It sets up the main window and providing a menubar, toolbar and statusbar. For the main view, an instance of class QPartView is created which creates your view.
Constructor & Destructor Documentation
QPartApp::QPartApp ()
construtor
References initActions(), initDoc(), initMenuBar(), initStatusBar(), initToolBar(), and initView().
QPartApp::~QPartApp ()
destructor
Member Function Documentation
void QPartApp::initActions ()
initializes all QActions of the application
References slotEditCopy(), slotEditCut(), slotEditPaste(), slotFileClose(), slotFileNew(), slotFileOpen(), slotFilePrint(), slotFileQuit(), slotFileSave(), slotHelpAbout(), slotPartConstraints(), slotPartRun(), slotViewStatusBar(), and slotViewToolBar().
Referenced by QPartApp().
void QPartApp::initDoc ()
setup the document
Referenced by QPartApp().
void QPartApp::initMenuBar ()
initMenuBar creates the menu_bar and inserts the menuitems
Referenced by QPartApp().
void QPartApp::initStatusBar ()
setup the statusbar
Referenced by QPartApp().
void QPartApp::initToolBar ()
this creates the toolbars. Change the toobar look and add new toolbars in this function
Referenced by QPartApp().
void QPartApp::initView ()
setup the mainview
Referenced by QPartApp().
bool QPartApp::queryExit ()
overloaded for Message box on last window exit
Referenced by slotFileQuit().
void QPartApp::slotEditCopy () [slot]
put the marked text/object into the clipboard
Referenced by initActions().
void QPartApp::slotEditCut () [slot]
put the marked text/object into the clipboard and remove it from the document
Referenced by initActions().
void QPartApp::slotEditPaste () [slot]
paste the clipboard into the document
Referenced by initActions().
void QPartApp::slotFileClose () [slot]
close the actual file
Referenced by initActions().
void QPartApp::slotFileNew () [slot]
generate a new document in the actual view
Referenced by initActions().
void QPartApp::slotFileOpen () [slot]
open a document
Referenced by initActions().
void QPartApp::slotFilePrint () [slot]
print the actual file
Referenced by initActions().
void QPartApp::slotFileQuit () [slot]
exits the application
References queryExit().
Referenced by initActions().
void QPartApp::slotFileSave () [slot]
save a document
Referenced by initActions().
void QPartApp::slotFileSaveAs () [slot]
save a document under a different filename
void QPartApp::slotHelpAbout () [slot]
shows an about dlg
Referenced by initActions().
void QPartApp::slotPartConstraints () [slot]
Partition constraints
Referenced by initActions().
void QPartApp::slotPartRun () [slot]
Partition run
References NetlistBase::cutCost(), and NetlistBase::getNumCells().
Referenced by initActions().
void QPartApp::slotViewStatusBar (bool toggle) [slot]
toggle the statusbar
Referenced by initActions().
void QPartApp::slotViewToolBar (bool toggle) [slot]
toggle the toolbar
Referenced by initActions().
The documentation for this class was generated from the following files:
qpart.h
qpart.cpp