PinForCellCursorTmpl< Cell_, Pin_ > Class Template Reference
PinForCellCursorTmpl< Cell_, Pin_ > Class Template Reference
Data Modeling Group.
#include <NetlistBase.hpp>
Public Member Functions
PinForCellCursorTmpl (Cell_ &n)
bool hasNext () const
void reset ()
Pin_ & getNext ()
Detailed Description
template<class Cell_, class Pin_ = Pin>
class PinForCellCursorTmpl< Cell_, Pin_ >
Cursor to traverse all the pins of one net/cell
Constructor & Destructor Documentation
template<class Cell_ , class Pin_ = Pin> PinForCellCursorTmpl< Cell_, Pin_ >::PinForCellCursorTmpl (Cell_ & n) [inline]
Constructor
Member Function Documentation
template<class Cell_ , class Pin_ = Pin> Pin_& PinForCellCursorTmpl< Cell_, Pin_ >::getNext () [inline]
Returns:
the next pin. Precondition: there exist the next item.
Reimplemented in NetCursorTmpl< Net_, Cell_, Pin_ >.
References PinForCellCursorTmpl< Cell_, Pin_ >::hasNext().
Referenced by NetlistBase::checkOk(), LayerAssignmentServ::doAssignment(), CycleRemovalServ::handleNextBest(), CycleRemovalServ::setup(), NetlistBase::writeDot(), and LayerAssignmentServ::writeDot().
template<class Cell_ , class Pin_ = Pin> bool PinForCellCursorTmpl< Cell_, Pin_ >::hasNext () const [inline]
Returns:
true if there exist a next item.
Referenced by NetlistBase::checkOk(), LayerAssignmentServ::doAssignment(), PinForCellCursorTmpl< Cell_, Pin_ >::getNext(), CycleRemovalServ::handleNextBest(), CycleRemovalServ::handleSink(), CycleRemovalServ::handleSrc(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), NetlistBase::readHMetis(), CycleRemovalServ::selectIndependentNets(), CycleRemovalServ::setup(), NetlistBaseTestCase::testNetCursor(), FMBiPartCore4::updateMove(), FMBiPartCore::updateMove(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore4::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore4::updateMoveSOED(), FMKWayPartCore::updateMoveSOED(), FMKWayPartCore::updateMoveSOEDCore(), NetlistBase::writeDot(), and LayerAssignmentServ::writeDot().
template<class Cell_ , class Pin_ = Pin> void PinForCellCursorTmpl< Cell_, Pin_ >::reset () [inline]
Reset cursor to the first position
The documentation for this class was generated from the following file:
NetlistBase.hpp