NetlistBaseTestCase Class Reference
NetlistBaseTestCase Class Reference
Qt Unit Test.
#include <NetlistBaseTest.hpp>
Public Member Functions
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
Protected Member Functions
void testCreate ()
void testCell ()
void testNet ()
void testPin ()
void testCellCursor ()
void testNetCursor ()
void testPinCursor ()
void testCutCost ()
void testCreate ()
void testCell ()
void testNet ()
void testPin ()
void testCellCursor ()
void testNetCursor ()
void testPinCursor ()
void testCutCost ()
void testCreate ()
void testCell ()
void testNet ()
void testPin ()
void testCellCursor ()
void testNetCursor ()
void testPinCursor ()
void testCutCost ()
Protected Attributes
NetlistBase * _H
Detailed Description
A test case for NetlistBase.
Member Function Documentation
void NetlistBaseTestCase::testCell () [protected]
Test Cell
References Cell::CELL, NetlistBase::getCell(), NetlistBase::getId(), Cell::getType(), Cell::getWeight(), Cell::isCluster(), Cell::isPad(), and Cell::isVisited().
void NetlistBaseTestCase::testCell () [protected]
Test Cell
void NetlistBaseTestCase::testCell () [protected]
Test Cell
void NetlistBaseTestCase::testCellCursor () [protected]
Test CellCursor
void NetlistBaseTestCase::testCellCursor () [protected]
Test CellCursor
References PinForNetCursorTmpl< Net_, Pin_ >::count(), NetlistBase::getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), and PinForNetCursorTmpl< Net_, Pin_ >::hasNext().
void NetlistBaseTestCase::testCellCursor () [protected]
Test CellCursor
void NetlistBaseTestCase::testCreate () [protected]
Test creation
void NetlistBaseTestCase::testCreate () [protected]
Test creation
void NetlistBaseTestCase::testCreate () [protected]
Test creation
References NetlistBase::checkOk(), NetlistBase::getMaxDegree(), NetlistBase::getNumCells(), NetlistBase::getNumNets(), NetlistBase::getNumPads(), NetlistBase::getNumPins(), NetlistBase::getTotalWeight(), and NetlistBase::hasFixedCells().
void NetlistBaseTestCase::testCutCost () [protected]
Test cut-cost
void NetlistBaseTestCase::testCutCost () [protected]
Test cut-cost
References NetlistBase::getNumCells(), NetlistBase::HyperEdgeCost(), NetlistBase::KMinus1Cost(), and NetlistBase::SOEDCost().
void NetlistBaseTestCase::testCutCost () [protected]
Test cut-cost
void NetlistBaseTestCase::testNet () [protected]
Test Net
void NetlistBaseTestCase::testNet () [protected]
Test Net
void NetlistBaseTestCase::testNet () [protected]
Test Net
References NetlistBase::getId(), NetlistBase::getNet(), Net::getWeight(), and Net::isVisited().
void NetlistBaseTestCase::testNetCursor () [protected]
Test NetCursor
void NetlistBaseTestCase::testNetCursor () [protected]
Test NetCursor
References NetlistBase::getCell(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), and PinForCellCursorTmpl< Cell_, Pin_ >::hasNext().
void NetlistBaseTestCase::testNetCursor () [protected]
Test NetCursor
void NetlistBaseTestCase::testPin () [protected]
Test Pin
void NetlistBaseTestCase::testPin () [protected]
Test Pin
void NetlistBaseTestCase::testPin () [protected]
Test Pin
void NetlistBaseTestCase::testPinCursor () [protected]
Test PinCursor
void NetlistBaseTestCase::testPinCursor () [protected]
Test PinCursor
void NetlistBaseTestCase::testPinCursor () [protected]
Test PinCursor
References NetlistBase::getNet(), PinForNetCursorTmpl< Net_, Pin_ >::getNext(), and PinForNetCursorTmpl< Net_, Pin_ >::hasNext().
The documentation for this class was generated from the following files:
cppunit/NetlistBaseTest.hpp
Testing/qtcppunit/NetlistBaseTest.hpp
Testing/unit/NetlistBaseTest.hpp
cppunit/NetlistBaseTest.cpp
Testing/qtcppunit/NetlistBaseTest.cpp
Testing/unit/NetlistBaseTest.cpp