GDListTestCase Class Reference
GDListTestCase Class Reference
Qt Unit Test.
#include <GDListTest.hpp>
Public Member Functions
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
Protected Member Functions
void testPushPop ()
void testCursor ()
void testConstCursor ()
void testPushPop ()
void testCursor ()
void testConstCursor ()
void testPushPop ()
void testCursor ()
void testConstCursor ()
Protected Attributes
GNode _d [4]
GDList< GNode > * _L1
GDList< GNode > * _L2
Detailed Description
A test case for GDList
Member Function Documentation
void GDListTestCase::testConstCursor () [protected]
Test constant cursor
void GDListTestCase::testConstCursor () [protected]
Test constant cursor
void GDListTestCase::testConstCursor () [protected]
Test constant cursor
References GDList< DNode >::clear(), GDListConstCursor< DNode >::getNext(), GDListConstCursor< DNode >::hasNext(), GDList< DNode >::isEmpty(), and GDList< DNode >::pushBack().
void GDListTestCase::testCursor () [protected]
Test cursor
void GDListTestCase::testCursor () [protected]
Test cursor
References GDList< DNode >::detach(), GDListCursor< DNode >::getNext(), GDListCursor< DNode >::hasNext(), GDList< DNode >::isEmpty(), and GDList< DNode >::pushBack().
void GDListTestCase::testCursor () [protected]
Test cursor
void GDListTestCase::testPushPop () [protected]
Test push/pop feature
References GDList< DNode >::isEmpty(), GDList< DNode >::popFront(), and GDList< DNode >::pushBack().
void GDListTestCase::testPushPop () [protected]
Test push/pop feature
void GDListTestCase::testPushPop () [protected]
Test push/pop feature
The documentation for this class was generated from the following files:
cppunit/GDListTest.hpp
Testing/qtcppunit/GDListTest.hpp
Testing/unit/GDListTest.hpp
cppunit/GDListTest.cpp
Testing/qtcppunit/GDListTest.cpp
Testing/unit/GDListTest.cpp