Cell Class Reference
Cell Class Reference
Data Modeling Group.
#include <Cell.hpp>
Public Types
enum Type { CELL, CLUSTER }
Public Member Functions
Cell ()
Type getType () const
void setCluster ()
bool isCluster () const
bool isPad () const
bool isFixed () const
void setFixed ()
void clrFixed ()
void toggleFixed ()
bool isVisited () const
void setVisited () const
void clrVisited () const
void toggleVisited ()
bool isLocked () const
void lock ()
void unlock ()
int getWeight () const
void setWeight (int weight)
Protected Member Functions
void setType (Type t)
Friends
class Netlist
class NetlistBase
Detailed Description
A cell class. In order to efficiently traverse the nets from cell, it is better that this class has a direct pointers to Net instead of going through the pin. It may make the FM algorithm a little faster. However, it prohibits to reuse the netlist from other algorithms that require to follow the signal direction.
Member Enumeration Documentation
enum Cell::Type
Node type enum.
Enumerator:
CELL
a cell
CLUSTER
a cluster
Constructor & Destructor Documentation
Cell::Cell () [inline]
Constructor
Member Function Documentation
void Cell::clrFixed () [inline]
Clear fixed.
Referenced by Netlist::setProxCells().
void Cell::clrVisited () const [inline]
Clear visited.
Referenced by NetlistBase::clrVisitedAllCells(), Netlist::minimumNetCover2(), and CycleRemovalServ::setup().
Type Cell::getType () const [inline]
Returns:
the type
Referenced by isCluster(), and NetlistBaseTestCase::testCell().
int Cell::getWeight () const [inline]
Returns:
node weight.
Referenced by Netlist::clusterSize(), FMKWayPartMgrBase::initPart(), Netlist::initWeightList(), isPad(), Netlist::isVILEOk(), KWayConstrMgr3::satisfied(), KWayConstrMgr::satisfied(), BiConstrMgr3::satisfied(), NetlistBaseTestCase::testCell(), KWayConstrMgrBase::updateMove(), and BiConstrMgrBase::updateMove().
bool Cell::isCluster () const [inline]
Returns:
true if this cell in fact is a cluster.
References CLUSTER, and getType().
Referenced by Netlist::projectUp(), and NetlistBaseTestCase::testCell().
bool Cell::isFixed () const [inline]
Returns:
true if node is fixed.
Referenced by Netlist::clusterSize(), NetlistBase::hasFixedCells(), FMKWayPartMgrBase::initPart(), Netlist::initWeightList(), Netlist::minimumNetCover2(), Netlist::minimumNetCoverOK(), Netlist::projectDown(), Netlist::projectUp(), and Netlist::setProxCells().
bool Cell::isLocked () const [inline]
Returns:
true if node is locked.
bool Cell::isPad () const [inline]
Returns:
true if cell is terminal pad.
References getWeight().
Referenced by NetlistBaseTestCase::testCell(), NetlistBase::writeDot(), LayerAssignmentServ::writeDot(), and NetlistBase::writeSol().
bool Cell::isVisited () const [inline]
Returns:
true if node is visited
Referenced by LayerAssignmentServ::doAssignment(), FMBiPartComm::initGain(), Netlist::markZeroPinNets(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), CycleRemovalServ::selectIndependentNets(), Netlist::setProxCells(), NetlistBaseTestCase::testCell(), and FMBiPartComm::updateMoveGeneralNet().
void Cell::lock () [inline]
Set locked.
void Cell::setCluster () [inline]
Set if this cell is a cluster.
References CLUSTER, and setType().
void Cell::setFixed () [inline]
Set fixed.
void Cell::setType (Type t) [inline, protected]
Set the type
Referenced by setCluster().
void Cell::setVisited () const [inline]
Set visited.
Referenced by LayerAssignmentServ::doAssignment(), CycleRemovalServ::handleNextBest(), CycleRemovalServ::handleSink(), CycleRemovalServ::handleSrc(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), CycleRemovalServ::selectIndependentNets(), and Netlist::setProxCells().
void Cell::setWeight (int weight) [inline]
Set node weight. Precondition: weight non-negative (>= 0)
References FMLimits::maxCellWeight().
Referenced by NetlistBase::readAre().
void Cell::toggleFixed () [inline]
Toggle fixed.
void Cell::toggleVisited () [inline]
Toggle visited.
void Cell::unlock () [inline]
Clear locked.
The documentation for this class was generated from the following file:
Cell.hpp