CycleRemovalServ Class Reference
CycleRemovalServ Class Reference
Cycle Removal Group.
#include <CycleRemovalServ.hpp>
Public Member Functions
CycleRemovalServ (Netlist &H)
Constructor.
~CycleRemovalServ ()
Destructor.
void doRemove ()
Perform the removal algorithm.
bool verifyOK ()
Verify only.
unsigned int selectIndependentNets (const std::vector< unsigned int > &netWeights)
Protected Member Functions
void setup ()
CycleRemovalServ (const CycleRemovalServ &)
CycleRemovalServ & operator= (const CycleRemovalServ &)
void handleSrc ()
Update neigbours.
void handleSink ()
void handleNextBest ()
void handleNetForSrc (Net &net)
void handleNetForSink (Net &net)
void assignFirstOrLastCell ()
void assignOtherCells ()
Protected Attributes
Netlist & _H
netlist to be handled
std::vector< int > _inDegreeCell
in-degree of cell
std::vector< int > _outDegreeCell
out-degree of cell
std::vector< int > _inDegreeNet
in-degree of net
std::vector< int > _outDegreeNet
out-degree of net
Vertex * _vertexArray
vertex array for bucket sort
GDList< Vertex > _srcQueue
event queue for source
GDList< Vertex > _sinkQueue
event queue for sink
GBPQueue< Vertex > * _bucketPQ
bounded priority queue
GDList< Vertex > _Sl
vertex sequence (left)
GDList< Vertex > _Sr
vertex sequence (right)
int _numHandledCells
keep track #cells handled
Detailed Description
Service for Remove Cycles of a netlist by reversing the direction of some pins. The algorithm is called Greedy-Cycle-Removal, which computes a vertex sequence inducing a small set of leftward edges. The algorithm runs in linear time and space, and it has a better guarantee on performance than a trivial method. We assume that the input netlist is connected; if not, we deal with each connected component individually. The algorithm successively removes vertices from , and adds each in turn, to one of two lists and . The vertices are added to either to the end of of or to the beginning of . When has been reduced to an empty digraph by successive removals, the output vertex sequence S is the concatenation of and .
The algorithm is greedy in its choice of the vertex to be removed from and the choice of the list (either or) to which it is added. All sinks should be added to , and all sources of should be added to , since this procedure will prevent their incident edges form becoming leftward edges. Note that an isolated vertex is both a sink and a source. In this implementation, we regard it as a sink and added to . After dealing with all sinks and sources, we choose a vertex for which is maximized. Vertex is removed and added to . The throught here is that this choice locally maximizes the number of "rightward" edges for a given number of leftward edges.
Member Function Documentation
void CycleRemovalServ::handleNextBest () [inline, protected]
Choose a vertex v such that the difference outDeg(v) - inDeg(v) is maximum, remove it from the queue, and append it to S_l.
References _bucketPQ, _H, _numHandledCells, _Sl, _vertexArray, NetlistBase::getCell(), Pin::getDirection(), Pin::getNet(), PinForCellCursorTmpl< Cell_, Pin_ >::getNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Pin::INPUT, Pin::OUTPUT, GBPQueue< BPQNode >::popFront(), GDList< DNode >::pushBack(), and Cell::setVisited().
Referenced by doRemove().
void CycleRemovalServ::handleSink () [inline, protected]
Choose a sink c, remove it from the sink queue, and prepend it to S_r. Note: isolated vertices are removed from the sink and prepended to S_r at this stage.
References _H, _numHandledCells, _sinkQueue, _Sr, _vertexArray, NetlistBase::getCell(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), GDList< DNode >::popFront(), GDList< DNode >::pushFront(), and Cell::setVisited().
Referenced by doRemove(), and verifyOK().
void CycleRemovalServ::handleSrc () [inline, protected]
Update neigbours.
Choose a source c, remove it from the source queue, and append it to S_l.
References _H, _numHandledCells, _Sl, _srcQueue, _vertexArray, NetlistBase::getCell(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), GDList< DNode >::popFront(), GDList< DNode >::pushBack(), and Cell::setVisited().
Referenced by doRemove(), and verifyOK().
unsigned int CycleRemovalServ::selectIndependentNets (const std::vector< unsigned int > & netWeights)
Select indepentent nets followed the signal flow
Select an independent set of nets based on signal flow (experimental).
References _H, _Sl, _vertexArray, Net::clrVisited(), NetlistBase::clrVisitedAllCells(), NetlistBase::clrVisitedAllNets(), GDList< DNode >::detach(), NetlistBase::getCell(), NetlistBase::getNet(), GDListCursor< DNode >::getNext(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), NetlistBase::getNumNets(), GDListCursor< DNode >::hasNext(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), GDList< DNode >::isEmpty(), Cell::isVisited(), Net::isVisited(), GDList< DNode >::popBack(), GDList< DNode >::pushBack(), Net::setVisited(), and Cell::setVisited().
void CycleRemovalServ::setup () [protected]
Initial Setup
References _bucketPQ, _H, _inDegreeCell, _inDegreeNet, _numHandledCells, _outDegreeCell, _outDegreeNet, _sinkQueue, _Sl, _Sr, _srcQueue, GDList< DNode >::clear(), Cell::clrVisited(), NetlistBase::getCell(), Pin::getDirection(), NetlistBase::getNet(), PinForCellCursorTmpl< Cell_, Pin_ >::getNext(), NetlistBase::getNumCells(), NetlistBase::getNumNets(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Pin::INPUT, Pin::OUTPUT, GBPQueue< BPQNode >::pushBackFast(), GDList< DNode >::pushRandom(), and GBPQueue< BPQNode >::resync().
Referenced by doRemove(), and verifyOK().
The documentation for this class was generated from the following files:
CycleRemovalServ.hpp
CycleRemovalServ.cpp