GBPQueue< BPQNode > Class Template Reference
GBPQueue< BPQNode > Class Template Reference
Data Structure Group
#include <GBPQueue.hpp>
Public Member Functions
GBPQueue (int a, int b)
Constructor.
~GBPQueue ()
void setUp (int a, int b)
Setup.
int getKey (const BPQNode &it) const
Get the key.
int getMax () const
bool isEmpty () const
bool isValid () const
void makeDummy ()
void clear ()
void pushBack (BPQNode &it, int k)
Insert item at the end of this queue.
void pushBackFast (BPQNode &it, int k)
Insert item at the end without update the max value.
void resync ()
Arbitrarily push item without update the max value.
BPQNode & popFront ()
void decreaseKeyLIFOBy (BPQNode &it, unsigned int m)
Decrease key by m. Precondition: PQ contains it.
void increaseKeyLIFOBy (BPQNode &it, unsigned int m)
Increase key by m. Precondition: PQ contains it.
void promote (BPQNode &it)
void demote (BPQNode &it)
void decreaseKeyBy (BPQNode &it, unsigned int m)
Decrease key by m. Precondition: PQ contains it.
void increaseKeyBy (BPQNode &it, unsigned int m)
Increase key by m. Precondition: PQ contains it.
void modifyKeyLIFOBy (BPQNode &it, int m)
Modify key by m. Precondition: PQ contains it.
void modifyKeyBy (BPQNode &it, int m)
Modify key by m. Precondition: PQ contains it.
void detach (BPQNode &it)
void pushTo (GDList< BPQNode > &list)
Friends
class GBPQueueCursor< BPQNode >
class GBPQueueConstCursor< BPQNode >
Detailed Description
template<class BPQNode>
class GBPQueue< BPQNode >
Bounded Priority Queue with integer keys in [a..b]. Implemented by array (bucket) of doubly-linked lists. Efficient if key is bounded by a small integer value. Note that this class does not own the PQ nodes, even though PQ node class is defined in this header file. This feature makes the nodes sharable between doubly linked list class and this class. In the FM algorithm, the node either attached to the gain buckets (PQ) or in the freeVertexList (doubly linked list), but not in both of them in the same time.
Another improvement is to make the array size one element bigger i.e. (b - a + 2). The extra dummy array element (which is T[0]) is used to reduce the boundary checking during updating.
All the member functions assume that the keys are within the bound.
Constructor & Destructor Documentation
template<class BPQNode > GBPQueue< BPQNode >::GBPQueue (int a, int b) [inline]
Constructor.
Parameters:
a lower bound
b upper bound Precondition: a <= b
template<class BPQNode> GBPQueue< BPQNode >::~GBPQueue () [inline]
Destructor.
Member Function Documentation
template<class BPQNode > void GBPQueue< BPQNode >::clear () [inline]
Reset the PQ.
template<class BPQNode> void GBPQueue< BPQNode >::decreaseKeyBy (BPQNode & it, unsigned int m)
Decrease key by m. Precondition: PQ contains it.
Parameters:
it the item
m the change of key Note that order of items with same key will be preserved. For FM algorithm, this is a prefered behavior.
References GDList< DNode >::detach().
template<class BPQNode> void GBPQueue< BPQNode >::decreaseKeyLIFOBy (BPQNode & it, unsigned int m)
Decrease key by m. Precondition: PQ contains it.
Parameters:
it the item
m the change of key Note that order of items with same key will not be preserved. For FM algorithm, this is a prefered behavior.
References GDList< DNode >::detach().
template<class BPQNode> void GBPQueue< BPQNode >::detach (BPQNode & it) [inline]
Detach the item from this queue. Precondition: PQ contains it
References GDList< DNode >::detach().
Referenced by GBPQueueTestCase::testCursors(), FMKWayGainMgr4::updateMove(), FMKWayGainMgr2::updateMove(), and FMBiGainMgr2::updateMove().
template<class BPQNode> int GBPQueue< BPQNode >::getKey (const BPQNode & it) const [inline]
Get the key.
Parameters:
it the item
Returns:
the key of it.
Referenced by FMKWayGainMgr4::getGain(), FMKWayGainMgr2::getGain(), FMBiGainMgr2::getGain(), and FMBiGainMgr::getGain().
template<class BPQNode> int GBPQueue< BPQNode >::getMax () const [inline]
Returns:
the max value.
template<class BPQNode> void GBPQueue< BPQNode >::increaseKeyBy (BPQNode & it, unsigned int m)
Increase key by m. Precondition: PQ contains it.
Parameters:
it the item
m the change of key Note that order of items with same key will be preserved. For FM algorithm, this is a prefered behavior.
References GDList< DNode >::detach().
template<class BPQNode> void GBPQueue< BPQNode >::increaseKeyLIFOBy (BPQNode & it, unsigned int m)
Increase key by m. Precondition: PQ contains it.
Parameters:
it the item
m the change of key Note that order of items with same key will not be preserved. For FM algorithm, this is a prefered behavior.
References GDList< DNode >::detach().
template<class BPQNode> bool GBPQueue< BPQNode >::isEmpty () const [inline]
Returns:
true if the PQ is empty.
Referenced by CycleRemovalServ::doRemove(), GBPQueueTestCase::testCursors(), and GBPQueueTestCase::testPushPop().
template<class BPQNode > bool GBPQueue< BPQNode >::isValid () const [inline]
Returns:
true if the PQ is valid. Take O(n) time.
template<class BPQNode> void GBPQueue< BPQNode >::makeDummy () [inline]
(For restricted used only) Make dummy.
template<class BPQNode> void GBPQueue< BPQNode >::modifyKeyBy (BPQNode & it, int m) [inline]
Modify key by m. Precondition: PQ contains it.
Parameters:
it the item
m the change of key Note that order of items with same key will be preserved. For FM algorithm, this is a prefered behavior.
Referenced by FMKWayGainMgr3::updateNeighbor(), and FMBiGainMgr3::updateNeighbor().
template<class BPQNode> void GBPQueue< BPQNode >::modifyKeyLIFOBy (BPQNode & it, int m) [inline]
Modify key by m. Precondition: PQ contains it.
Parameters:
it the item
m the change of key Note that order of items with same key will not be preserved. For FM algorithm, this is a prefered behavior.
Referenced by FMKWayGainMgr4::updateNeighbor(), FMKWayGainMgr2::updateNeighbor(), FMBiGainMgr2::updateNeighbor(), and FMBiGainMgr::updateNeighbor().
template<class BPQNode > BPQNode & GBPQueue< BPQNode >::popFront () [inline]
Pop an item with highest key. Precondition: PQ is not empty.
Referenced by CycleRemovalServ::handleNextBest(), and GBPQueueTestCase::testPushPop().
template<class BPQNode> void GBPQueue< BPQNode >::pushBack (BPQNode & it, int k) [inline]
Insert item at the end of this queue.
Parameters:
it the item
k the key Precondition: PQ does not contain it; a <= k <= b.
Referenced by FMKWayGainMgr4::pushBack(), FMKWayGainMgr2::pushBack(), FMBiGainMgr2::pushBack(), FMBiGainMgr::pushBack(), GBPQueueTestCase::testCursors(), and GBPQueueTestCase::testPushPop().
template<class BPQNode> void GBPQueue< BPQNode >::pushBackFast (BPQNode & it, int k) [inline]
Insert item at the end without update the max value.
Parameters:
it the item
k the key Precondition: PQ does not contain it; a <= k <= b. Call resync() after calling this method.
Referenced by Netlist::firstChoice(), Netlist::maximumIndependentSet(), and CycleRemovalServ::setup().
template<class BPQNode> void GBPQueue< BPQNode >::pushTo (GDList< BPQNode > & list) [inline]
Push all the items into a given list. This BPQueue becomes empty after this operation.
References GDList< DNode >::concat().
Referenced by Netlist::firstChoice(), and Netlist::maximumIndependentSet().
template<class BPQNode > void GBPQueue< BPQNode >::resync () [inline]
Arbitrarily push item without update the max value.
Parameters:
it the item
k the key Precondition: PQ does not contain it; a <= k <= b. Call resync() after calling this method. Update the max value
Referenced by Netlist::firstChoice(), Netlist::maximumIndependentSet(), and CycleRemovalServ::setup().
template<class BPQNode > void GBPQueue< BPQNode >::setUp (int a, int b) [inline]
Setup.
Parameters:
a lower bound
b upper bound Precondition: a <= b
Referenced by FMBiGainMgr::FMBiGainMgr(), FMBiGainMgr2::FMBiGainMgr2(), FMKWayGainMgr2::FMKWayGainMgr2(), FMKWayGainMgr4::FMKWayGainMgr4(), and GBPQueue2< BPQNode >::setUp().
The documentation for this class was generated from the following file:
GBPQueue.hpp