FMKWayPartCore Class Reference
FMKWayPartCore Class Reference
Multi-Way Partitioner Core Engine
#include <FMKWayPartCore.hpp>
Public Member Functions
template<class MoveStruct >
void updateMove (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveHEdge (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveKMinus1 (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveKMinus1Core (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveSOED (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveSOEDCore (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
Protected Member Functions
FMKWayPartCore (const FMParam &param)
void initGainCore (const std::vector< unsigned char > &part)
void updateNetStatus ()
template<class MoveStruct >
void updateMove (const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
int updateCore (const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo)
Detailed Description
FM Multi-way Partitioning Core. This class is mainly for calculating the initial gain and calculating the amount of the gain change (delta gain) according to the move.
Constructor & Destructor Documentation
FMKWayPartCore::FMKWayPartCore (const FMParam & param) [protected]
Constructor
Member Function Documentation
void FMKWayPartCore::initGainCore (const std::vector< unsigned char > & part) [protected]
Setup the initial gain. Also setup the gain buckets data structure. Take O(n) time.
template<class MoveStruct > void FMKWayPartCore::updateMove (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the gain structure given the moving vertex
References FMKWayPartMgrBase::getCostModel().
template<class MoveStruct > void FMKWayPartCore::updateMove (const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure given the moving vertex
template<class MoveStruct > void FMKWayPartCore::updateMoveHEdge (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in hyperedge metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, FMKWayPartComm::_num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), FMKWayPartMgrBase::getNumPartitions(), Net::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetHEdge().
template<class MoveStruct > void FMKWayPartCore::updateMoveKMinus1 (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in (K-1) metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, FMKWayPartComm::_num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), FMKWayPartMgrBase::getNumPartitions(), Net::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetKMinus1().
template<class MoveStruct > void FMKWayPartCore::updateMoveKMinus1Core (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in (K-1) metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, FMKWayPartComm::_num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), FMKWayPartMgrBase::getNumPartitions(), Net::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetKMinus14().
template<class MoveStruct > void FMKWayPartCore::updateMoveSOED (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in SOED metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, FMKWayPartComm::_num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), FMKWayPartMgrBase::getNumPartitions(), Net::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetSOED().
template<class MoveStruct > void FMKWayPartCore::updateMoveSOEDCore (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in SOED metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, FMKWayPartComm::_num, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), FMKWayPartMgrBase::getNumPartitions(), Net::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetSOED4().
The documentation for this class was generated from the following files:
FMKWayPartCore.hpp
FMBiPartCore.cpp
FMKWayPartCore.cpp