GDListCursor< DNode > Class Template Reference
GDListCursor< DNode > Class Template Reference
Data Structure Group
#include <GDList.hpp>
Public Member Functions
GDListCursor ()
GDListCursor (GDList< DNode > &L)
void associate (GDList< DNode > &L)
bool hasNext () const
void reset ()
DNode & getNext ()
Detailed Description
template<class DNode>
class GDListCursor< DNode >
List Cursor. Traverse the list from the first item. Usually it is safe to attach/detach list items during the cursor is active.
Constructor & Destructor Documentation
template<class DNode> GDListCursor< DNode >::GDListCursor () [inline]
Default Constructor
template<class DNode> GDListCursor< DNode >::GDListCursor (GDList< DNode > & L) [inline]
Constructor
Member Function Documentation
template<class DNode> void GDListCursor< DNode >::associate (GDList< DNode > & L) [inline]
Associate to the list L and reset the cursor.
Referenced by GBPQueueCursor< Vertex >::getNext(), and GBPQueueCursor< Vertex >::reset().
template<class DNode> DNode& GDListCursor< DNode >::getNext () [inline]
Returns:
the next item. Precondition: next item exist
Referenced by GMultiSet< T >::ascendingOrder(), LayerAssignmentServ::doAssignment(), Netlist::firstChoice(), GBPQueueCursor< Vertex >::getNext(), Netlist::isVILEOk(), Netlist::maximumIndependentSet(), CycleRemovalServ::selectIndependentNets(), and GDListTestCase::testCursor().
template<class DNode> bool GDListCursor< DNode >::hasNext () const [inline]
Returns:
true if there is a next item.
Referenced by GMultiSet< T >::ascendingOrder(), LayerAssignmentServ::doAssignment(), Netlist::firstChoice(), GDListCursor< Vertex >::getNext(), GBPQueueCursor< Vertex >::getNext(), Netlist::isVILEOk(), Netlist::maximumIndependentSet(), CycleRemovalServ::selectIndependentNets(), and GDListTestCase::testCursor().
template<class DNode> void GDListCursor< DNode >::reset () [inline]
Reset the cursor to the first position.
Referenced by GDListCursor< Vertex >::associate().
The documentation for this class was generated from the following file:
GDList.hpp