FMKWayPartCore4 Class Reference
FMKWayPartCore4 Class Reference
Multi-Way Partitioner Core Engine
#include <FMKWayPartCore4.hpp>
Public Member Functions
template<class MoveStruct >
void updateMove (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveHEdge (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveKMinus1 (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveSOED (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
Protected Member Functions
FMKWayPartCore4 (const FMParam &param)
void initGainCore (const std::vector< unsigned char > &part)
void updateNetStatus ()
template<class MoveStruct >
void updateMove (const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class GainMgr >
void updateMove4 (const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, GainMgr &gainMgr)
template<class GainMgr >
void pushBack4 (unsigned int toPart, const Cell &v, GainMgr &gainMgr)
Detailed Description
FM Multi-way Partitioning Core (version 4). This class is mainly for calculating the initial gain and calculating the amount of the gain change (delta gain) according to the move. This class is tailored for refinement manager.
Constructor & Destructor Documentation
FMKWayPartCore4::FMKWayPartCore4 (const FMParam & param) [protected]
Constructor
References FMPartMgrBase::getNumNets(), and FMKWayPartMgrBase::getNumPartitions().
Member Function Documentation
void FMKWayPartCore4::initGainCore (const std::vector< unsigned char > & part) [protected]
Setup the initial gain. Also setup the gain buckets data structure. Take O(n) time.
Initialize the gain structure (c.f. Sarrafzadeh and Wong, page 38)
References FMBiPartComm::_gain, FMPartMgrBase::_netList, FMPartMgrBase::getNumNets(), FMBiPartComm::initGain(), and Net::isHighFanout().
template<class GainMgr > void FMKWayPartCore4::pushBack4 (unsigned int toPart, const Cell & v, GainMgr & gainMgr) [inline, protected]
Push back the vertex to the gain manager (special for refinement code)
References FMPartMgrBase::_cellList, FMKWayPartComm::_gain, and FMKWayPartMgrBase::getNumPartitions().
template<class MoveStruct > void FMKWayPartCore4::updateMove (const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure given the moving vertex
Referenced by updateMove4().
template<class MoveStruct > void FMKWayPartCore4::updateMove (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the gain structure given the moving vertex
References FMKWayPartComm::_deltaGainV, FMKWayPartMgrBase::getCostModel(), and FMKWayPartMgrBase::getNumPartitions().
template<class GainMgr > void FMKWayPartCore4::updateMove4 (const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, GainMgr & gainMgr) [inline, protected]
Update the gain structure given the moving vertex (special for refinement code)
References FMKWayPartComm::_gain, FMKWayPartMgrBase::getNumPartitions(), and updateMove().
template<class MoveStruct > void FMKWayPartCore4::updateMoveHEdge (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in hyperedge metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMMoveInfo::_fromPart, FMPartMgrBase::_netList, FMKWayPartComm::_num, FMMoveInfo::_toPart, PinForNetCursorTmpl< Net_, Pin_ >::count(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), FMKWayPartMgrBase::getNumPartitions(), Net::getWeight(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetHEdge4().
template<class MoveStruct > void FMKWayPartCore4::updateMoveKMinus1 (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in (K-1) metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMMoveInfo::_fromPart, FMPartMgrBase::_netList, FMKWayPartComm::_num, FMMoveInfo::_toPart, PinForNetCursorTmpl< Net_, Pin_ >::count(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), Net::getWeight(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetKMinus14().
template<class MoveStruct > void FMKWayPartCore4::updateMoveSOED (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in SOED metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_cell, FMMoveInfo::_fromPart, FMPartMgrBase::_netList, FMKWayPartComm::_num, FMMoveInfo::_toPart, PinForNetCursorTmpl< Net_, Pin_ >::count(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), FMKWayPartMgrBase::getNumPartitions(), Net::getWeight(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), and FMKWayPartComm::updateMoveGeneralNetSOED4().
The documentation for this class was generated from the following files:
FMKWayPartCore4.hpp
FMBiPartCore.cpp
FMBiPartCore4.cpp
FMKWayPartCore.cpp
FMKWayPartCore4.cpp