BiConstrMgr3 Class Reference
BiConstrMgr3 Class Reference
Bi-partitioner Core Engine
#include <BiConstrMgr3.hpp>
Public Member Functions
bool satisfied (const Cell &cell, unsigned int fromPart, unsigned int toPart) const
Check if the moved is OK.
Detailed Description
Bi-partitioning Constraints Manager (version 3). Mainly to answer question "Is a vertex allowed to move from one partition to another?". In this version, we relax the constraint so that a cell can move if it is not increasing the violation of the constraints. Although the performance in general is better than the traditional approach, the final result may not guarantee to be satisfied the constraints.
See also:
BiConstrMgr
Member Function Documentation
bool BiConstrMgr3::satisfied (const Cell & cell, unsigned int fromPart, unsigned int toPart) const [inline]
Check if the moved is OK.
Returns:
true if the move is OK.
Parameters:
cell the cell.
fromPart partition that the cell will move from.
toPart partition that the cell will move to. In this version, we relax the constraint so that a cell can move if it is not increasing the violation of the constraints. See the discussion of the VILE in the UCLA's paper.
References BiConstrMgrBase::_diff, BiConstrMgrBase::_lowerBound, and Cell::getWeight().
Referenced by FMBiGainMgr2::select(), and FMKWayGainMgr4::select().
The documentation for this class was generated from the following file:
BiConstrMgr3.hpp