FMKWayPartComm Class Reference
FMKWayPartComm Class Reference
Multi-Way Partitioner Core Engine
#include <FMKWayPartComm.hpp>
Public Member Functions
template<class MoveStruct >
void updateMove2PinNet (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, int weight, MoveStruct &ms)
template<class MoveStruct >
void updateMove2PinNet4 (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, int weight, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetHEdge4 (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetHEdge (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetCommHEdge (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetKMinus14 (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetKMinus1 (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetCommKMinus1 (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetSOED (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetSOED4 (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetCommSOED (const Net &e, const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
Protected Member Functions
FMKWayPartComm (const FMParam &param)
void initGainKMinus1 (const Net &e, const std::vector< unsigned char > &part)
void initGainSOED (const Net &e, const std::vector< unsigned char > &part)
void initGainHEdge (const Net &e, const std::vector< unsigned char > &part)
template<class MoveStruct >
void updateMove2PinNet (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, int weight, MoveStruct &ms)
template<class MoveStruct >
void updateMove2PinNet4 (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, int weight, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetHEdge (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetHEdge4 (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetKMinus1 (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetKMinus14 (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetSOED (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class MoveStruct >
void updateMoveGeneralNetSOED4 (const Net &e, const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
int getGain (const FMMoveInfo &moveInfo) const
Protected Attributes
std::vector< short > _gain [_M]
int _num [_M]
short _deltaGainV [_M]
Detailed Description
FM Multi-way Partitioning Common Utility. This class is mainly reponsible for calculating the initial gain and calculating the amount of the gain change (delta gain) according to the move.
Constructor & Destructor Documentation
FMKWayPartComm::FMKWayPartComm (const FMParam & param) [protected]
Constructor
References _gain, FMPartMgrBase::getNetlist(), FMPartMgrBase::getNumCells(), FMKWayPartMgrBase::getNumPartitions(), and Netlist::initVertexArray().
Member Function Documentation
int FMKWayPartComm::getGain (const FMMoveInfo & moveInfo) const [inline, protected]
Returns:
the gain of the moving cell
References _gain, FMMoveInfo::_i_v, and FMMoveInfo::_toPart.
void FMKWayPartComm::initGainHEdge (const Net & e, const std::vector< unsigned char > & part) [protected]
Setup the initial gain with hyperedge metric. Also setup the gain buckets data structure. Take O(n) time.
References _num, PinForNetCursorTmpl< Net_, Pin_ >::count(), FMKWayPartMgrBase::getNumPartitions(), and Net::getWeight().
void FMKWayPartComm::initGainKMinus1 (const Net & e, const std::vector< unsigned char > & part) [protected]
Setup the initial gain with (K-1) metric. Also setup the gain buckets data structure. Take O(n) time.
Note that the code for (K-1) metric looks similar to the bi-partitioning code. Setting the initial gain for each net. Here, we use the (K-1) metric cost model.
References _num, PinForNetCursorTmpl< Net_, Pin_ >::count(), FMKWayPartMgrBase::getNumPartitions(), and Net::getWeight().
void FMKWayPartComm::initGainSOED (const Net & e, const std::vector< unsigned char > & part) [protected]
Setup the initial gain with SOED metric. Also setup the gain buckets data structure. Take O(n) time.
Note that SOED cost is equal to the (K-1) cost plus the Hyper Edge cost.
References _num, PinForNetCursorTmpl< Net_, Pin_ >::count(), FMKWayPartMgrBase::getNumPartitions(), and Net::getWeight().
template<class MoveStruct > void FMKWayPartComm::updateMove2PinNet (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, int weight, MoveStruct & ms)
Update the neighbors structure according to the move.
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, FMMoveInfo::_fromPart, FMMoveInfo::_toPart, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), and FMKWayPartMgrBase::getNumPartitions().
template<class MoveStruct > void FMKWayPartComm::updateMove2PinNet4 (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, int weight, MoveStruct & ms)
Update the structures (both neighbors and the moving cell) according to the move.
References FMMoveInfo::_cell, FMPartMgrBase::_cellList, _deltaGainV, FMMoveInfo::_fromPart, FMMoveInfo::_toPart, PinForNetCursorTmpl< Net_, Pin_ >::count(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), and FMKWayPartMgrBase::getNumPartitions().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetCommKMinus1 (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [inline]
Update the structure according to the move. The gains are measured in (K-1) metric.
References FMMoveInfo::_cell, FMMoveInfo::_fromPart, _num, FMMoveInfo::_toPart, FMKWayPartMgrBase::getNumPartitions(), and Net::getWeight().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetHEdge (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the structure according to the move. The gains are measured in hyperedge metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References FMMoveInfo::_fromPart, _num, and FMMoveInfo::_toPart.
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetHEdge (const Net & e, const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure with hyperedge metric given the moving vertex
Referenced by FMKWayPartCore::updateMoveHEdge().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetHEdge4 (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the structure according to the move. The gains are measured in hyperedge metric. Note that I can think of other possible ways to perform the same function. However, don't know which way can be the fastest one.
References _deltaGainV, FMMoveInfo::_fromPart, _num, FMMoveInfo::_toPart, FMKWayPartMgrBase::getNumPartitions(), and Net::getWeight().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetHEdge4 (const Net & e, const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure with hyperedge metric given the moving vertex
Referenced by FMKWayPartCore4::updateMoveHEdge().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetKMinus1 (const Net & e, const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure with (K-1) metric given the moving vertex
Referenced by FMKWayPartCore::updateMoveKMinus1().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetKMinus1 (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the structure according to the move. The gains are measured in (K-1) metric.
References FMMoveInfo::_fromPart, _num, and FMMoveInfo::_toPart.
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetKMinus14 (const Net & e, const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure with (K-1) metric given the moving vertex
Referenced by FMKWayPartCore4::updateMoveKMinus1(), and FMKWayPartCore::updateMoveKMinus1Core().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetKMinus14 (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the structure according to the move. The gains are measured in (K-1) metric.
References _deltaGainV, FMMoveInfo::_fromPart, _num, FMMoveInfo::_toPart, FMKWayPartMgrBase::getNumPartitions(), and Net::getWeight().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetSOED (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the structure according to the move. The gains are measured in SOED metric.
References FMMoveInfo::_fromPart, _num, and FMMoveInfo::_toPart.
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetSOED (const Net & e, const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure with SOED metric given the moving vertex
Referenced by FMKWayPartCore::updateMoveSOED().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetSOED4 (const Net & e, const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms) [protected]
Update the gain structure with SOED metric given the moving vertex
Referenced by FMKWayPartCore4::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
template<class MoveStruct > void FMKWayPartComm::updateMoveGeneralNetSOED4 (const Net & e, const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
Update the structure according to the move. The gains are measured in SOED metric.
References _deltaGainV, FMMoveInfo::_fromPart, _num, FMMoveInfo::_toPart, FMKWayPartMgrBase::getNumPartitions(), and Net::getWeight().
Member Data Documentation
short FMKWayPartComm::_deltaGainV[_M] [protected]
gain change of the moving cell
Referenced by FMKWayPartCore4::updateMove(), updateMove2PinNet4(), updateMoveGeneralNetHEdge4(), updateMoveGeneralNetKMinus14(), and updateMoveGeneralNetSOED4().
std::vector<short> FMKWayPartComm::_gain[_M] [protected]
gain of each node
Referenced by FMKWayPartComm(), getGain(), FMKWayPartCore4::pushBack4(), and FMKWayPartCore4::updateMove4().
int FMKWayPartComm::_num[_M] [protected]
number of vertices on each partitions
Referenced by initGainHEdge(), initGainKMinus1(), initGainSOED(), updateMoveGeneralNetCommKMinus1(), updateMoveGeneralNetHEdge(), updateMoveGeneralNetHEdge4(), updateMoveGeneralNetKMinus1(), updateMoveGeneralNetKMinus14(), updateMoveGeneralNetSOED(), updateMoveGeneralNetSOED4(), FMKWayPartCore4::updateMoveHEdge(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore4::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore4::updateMoveSOED(), FMKWayPartCore::updateMoveSOED(), and FMKWayPartCore::updateMoveSOEDCore().
The documentation for this class was generated from the following files:
FMKWayPartComm.hpp
FMKWayPartComm.cpp