GBPQueueTestCase Class Reference
GBPQueueTestCase Class Reference
Qt Unit Test.
#include <GBPQueueTest.hpp>
Public Member Functions
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
Protected Member Functions
void testPushPop ()
void testCursors ()
void testPushPop ()
void testCursors ()
void testPushPop ()
void testCursors ()
Protected Attributes
GNode _d [6]
GBPQueue< GNode > * _PQ1
GBPQueue< GNode > * _PQ2
Detailed Description
A test case for GBPQueue
Member Function Documentation
void GBPQueueTestCase::testCursors () [protected]
Test cursors
References GBPQueue< BPQNode >::detach(), GBPQueueCursor< BPQNode >::getNext(), GBPQueueCursor< BPQNode >::hasNext(), GBPQueue< BPQNode >::isEmpty(), and GBPQueue< BPQNode >::pushBack().
void GBPQueueTestCase::testCursors () [protected]
Test cursors
void GBPQueueTestCase::testCursors () [protected]
Test cursors
void GBPQueueTestCase::testPushPop () [protected]
Test push/pop feature
void GBPQueueTestCase::testPushPop () [protected]
Test push/pop feature
void GBPQueueTestCase::testPushPop () [protected]
Test push/pop feature
References GBPQueue< BPQNode >::isEmpty(), GBPQueue< BPQNode >::popFront(), and GBPQueue< BPQNode >::pushBack().
The documentation for this class was generated from the following files:
cppunit/GBPQueueTest.hpp
Testing/qtcppunit/GBPQueueTest.hpp
Testing/unit/GBPQueueTest.hpp
cppunit/GBPQueueTest.cpp
Testing/qtcppunit/GBPQueueTest.cpp
Testing/unit/GBPQueueTest.cpp