CellCursorTmpl< Cell_, Net_, Pin_ > Class Template Reference
CellCursorTmpl< Cell_, Net_, Pin_ > Class Template Reference
Data Modeling Group.
#include <NetlistBase.hpp>
Public Member Functions
CellCursorTmpl (Net_ &n)
Cell_ & getNext ()
Detailed Description
template<class Cell_, class Net_, class Pin_ = Pin>
class CellCursorTmpl< Cell_, Net_, Pin_ >
Cursor to traverse all the cells of one net. Since there is no direct pointer to the cells (need to go through pin). It may make the FM algorithm a little slower than the highly tuned implementation.
Constructor & Destructor Documentation
template<class Cell_ , class Net_ , class Pin_ = Pin> CellCursorTmpl< Cell_, Net_, Pin_ >::CellCursorTmpl (Net_ & n) [inline]
Constructor
Member Function Documentation
template<class Cell_ , class Net_ , class Pin_ = Pin> Cell_& CellCursorTmpl< Cell_, Net_, Pin_ >::getNext () [inline]
Returns:
the next cell. This function is crucial in FM algorithm. Precondition: there exist the next item.
Reimplemented from PinForNetCursorTmpl< Net_, Pin_ >.
Referenced by Netlist::clusterSize(), NetlistBase::cutCost(), NetlistBase::HyperEdgeCost(), FMBiPartComm::initGain(), Netlist::markZeroPinNets(), Netlist::maximumIndependentSet(), Netlist::minimumNetCover(), Netlist::minimumNetCover2(), Netlist::projectUp(), CycleRemovalServ::selectIndependentNets(), Netlist::setFixedNets(), NetlistBaseTestCase::testCellCursor(), FMBiPartCore::updateMove(), FMKWayPartComm::updateMove2PinNet(), FMBiPartComm::updateMove2PinNet(), FMKWayPartComm::updateMove2PinNet4(), FMBiPartComm::updateMoveGeneralNet(), FMKWayPartCore::updateMoveHEdge(), FMKWayPartCore::updateMoveKMinus1(), FMKWayPartCore::updateMoveKMinus1Core(), FMKWayPartCore::updateMoveSOED(), FMKWayPartCore::updateMoveSOEDCore(), and NetlistBase::writeHMetis().
The documentation for this class was generated from the following file:
NetlistBase.hpp