NetlistTestCase Class Reference
NetlistTestCase Class Reference
Qt Unit Test.
#include <NetlistTest.hpp>
Public Member Functions
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
void setUp ()
void tearDown ()
Protected Member Functions
void testMNC ()
void testMIS ()
void testContraction ()
void testProjection ()
void testMNC ()
void testMIS ()
void testContraction ()
void testProjection ()
void testMNC ()
void testMIS ()
void testContraction ()
void testProjection ()
Protected Attributes
Netlist * _H
Detailed Description
A test case for Netlist
Member Function Documentation
void NetlistTestCase::testContraction () [protected]
Test contraction methods
void NetlistTestCase::testContraction () [protected]
Test contraction methods
References NetlistBase::clrFixedAllNets(), Netlist::contractByFC(), Netlist::contractByMMC(), Netlist::contractByRandom(), and Netlist::contractPhase2().
void NetlistTestCase::testContraction () [protected]
Test contraction methods
void NetlistTestCase::testMIS () [protected]
Test maximum independent set
void NetlistTestCase::testMIS () [protected]
Test maximum independent set
void NetlistTestCase::testMIS () [protected]
Test maximum independent set
References Netlist::clusterSize(), NetlistBase::getNumNets(), Netlist::maximumIndependentSet(), and Netlist::maximumIndependentSetOK().
void NetlistTestCase::testMNC () [protected]
Test minimum net cover
void NetlistTestCase::testMNC () [protected]
Test minimum net cover
void NetlistTestCase::testMNC () [protected]
Test minimum net cover
References Netlist::clusterSize(), NetlistBase::getNumNets(), Netlist::minimumNetCover(), and Netlist::minimumNetCoverOK().
void NetlistTestCase::testProjection () [protected]
Test projection methods
References Netlist::contractByMMC(), Netlist::contractPhase2(), NetlistBase::getNumCells(), Netlist::projectDown(), and Netlist::setFixedNets().
void NetlistTestCase::testProjection () [protected]
Test projection methods
void NetlistTestCase::testProjection () [protected]
Test projection methods
The documentation for this class was generated from the following files:
cppunit/NetlistTest.hpp
Testing/qtcppunit/NetlistTest.hpp
Testing/unit/NetlistTest.hpp
cppunit/NetlistTest.cpp
Testing/qtcppunit/NetlistTest.cpp
Testing/unit/NetlistTest.cpp