GMultiSet< T > Class Template Reference
GMultiSet< T > Class Template Reference
Data Structure Group
#include <GMultiSet.hpp>
Public Types
typedef GTreeNode< T > GTreeItem
Public Member Functions
GMultiSet ()
~GMultiSet ()
T getKey (const GMultiSetItem &it) const
bool isEmpty () const
void clear ()
void insert (GMultiSetItem &elem, T k)
void insertFront (GMultiSetItem &elem, T k)
GDList< GMultiSetItem > * decendingOrder ()
GDList< GMultiSetItem > * ascendingOrder ()
Detailed Description
template<class T>
class GMultiSet< T >
A MutliSet (under construction).
Member Typedef Documentation
template<class T> typedef GTreeNode<T> GMultiSet< T >::GTreeItem
Tree item
Constructor & Destructor Documentation
template<class T> GMultiSet< T >::GMultiSet () [inline]
Constructor
template<class T> GMultiSet< T >::~GMultiSet () [inline]
Destructor
Member Function Documentation
template<class T > GDList< GMultiSetItem > * GMultiSet< T >::ascendingOrder ()
Convert this set to a sorted list in ascending order. This set will be invalid after this operation. Caller need to delete the list after use
References GDList< DNode >::concat(), GDListCursor< DNode >::getNext(), GDListCursor< DNode >::hasNext(), and GBTree< TNode >::infixOrder().
template<class T> void GMultiSet< T >::clear () [inline]
Reset the MultiSet
Reimplemented from GBTree< GTreeNode< T > >.
template<class T > GDList< GMultiSetItem > * GMultiSet< T >::decendingOrder ()
Convert this set to a sorted list in decending order. This set will be invalid after this operation. Caller need to delete the list after use
References GDList< DNode >::concat(), and GBTree< TNode >::infixOrder().
template<class T> T GMultiSet< T >::getKey (const GMultiSetItem & it) const [inline]
Returns:
the key of it
References GNode::_key.
template<class T > void GMultiSet< T >::insert (GMultiSetItem & elem, T k)
Insert an element
References GDList< DNode >::pushBack().
template<class T > void GMultiSet< T >::insertFront (GMultiSetItem & elem, T k)
Insert an element in LIFO fashion
References GDList< DNode >::pushFront().
template<class T> bool GMultiSet< T >::isEmpty () const [inline]
Returns:
true if the tree is empty
Reimplemented from GBTree< GTreeNode< T > >.
The documentation for this class was generated from the following file:
GMultiSet.hpp