Node Class Reference
Node Class Reference
Data Modeling Group.
#include <Node.hpp>
Public Member Functions
Node ()
Pin * firstAdjPin ()
const Pin * firstAdjPin () const
Friends
class Netlist
class NetlistBase
Detailed Description
A node class. In order to efficiently traverse the nets from cell, it is better that this class has a direct pointers to Net instead of going through the pin. It may make the FM algorithm a little faster. However, it prohibits to reuse the netlist from other algorithms that require to follow the signal direction.
Constructor & Destructor Documentation
Node::Node () [inline]
Constructor
Member Function Documentation
Pin* Node::firstAdjPin () [inline]
Returns:
the firstAdjacency pin
Referenced by NetlistBase::checkOk(), Net::isHighFanout(), and Netlist::projectUp().
const Pin* Node::firstAdjPin () const [inline]
Returns:
the firstAdjacency pin
The documentation for this class was generated from the following file:
Node.hpp