FMKWayGainMgr4 Class Reference
FMKWayGainMgr4 Class Reference
Multi-Way Partitioner Core Engine
#include <FMKWayGainMgr4.hpp>
Public Member Functions
FMKWayGainMgr4 (const FMParam &param)
void init (const std::vector< unsigned char > &part, std::vector< short > *gain)
Vertex * select (FMMoveInfo &moveInfo, const std::vector< unsigned char > &part, KWayConstrMgr3 &constrMgr)
int getGain (const FMMoveInfo &mInfo) const
void updateMove (const FMMoveInfo &moveInfo, const short *=0)
void updateNeighbor (unsigned int whichPart, unsigned int i_w, const short *deltaGain)
void pushBack (unsigned int whichPart, unsigned int i_w, const short *gain)
void updateGain (const std::vector< unsigned char > &part, std::vector< short > *gain)
Protected Member Functions
unsigned int getNumPartitions () const
Protected Attributes
Netlist & _H
unsigned int _K
VertexPQ _gainBucket [_M][_M]
VertexPQCur _gainBucketCur [_M][_M]
std::vector< Vertex > _vertexArray [_M]
Cell *const _cellList
Detailed Description
FM Multi-way Partitioning Gain Manager. This class responsible for maintaining the gain bucket structures and helps to select the best vertex. In this version, K(K-1) bucket arrays are used, one for each partition.
See also:
FMBiGainMgr2.
Constructor & Destructor Documentation
FMKWayGainMgr4::FMKWayGainMgr4 (const FMParam & param)
Constructor
References FMParam::_cm, _gainBucket, _gainBucketCur, _H, _K, _vertexArray, GBPQueueCursor< BPQNode >::associate(), NetlistBase::getMaxDegree(), NetlistBase::getNumCells(), getNumPartitions(), and GBPQueue< BPQNode >::setUp().
Member Function Documentation
int FMKWayGainMgr4::getGain (const FMMoveInfo & mInfo) const [inline]
Returns:
the gain of vertex if it moves from fromPart to toPart
References FMMoveInfo::_fromPart, _gainBucket, FMMoveInfo::_i_v, FMMoveInfo::_toPart, _vertexArray, and GBPQueue< BPQNode >::getKey().
unsigned int FMKWayGainMgr4::getNumPartitions () const [inline, protected]
Returns:
the number of partitions.
References _K.
Referenced by FMKWayGainMgr4(), pushBack(), updateMove(), and updateNeighbor().
void FMKWayGainMgr4::init (const std::vector< unsigned char > & part, std::vector< short > * gain)
Setup the gain bucket structure
Referenced by updateGain().
void FMKWayGainMgr4::pushBack (unsigned int whichPart, unsigned int i_w, const short * gain) [inline]
Push back the vertices of cell i_w to the gain manager.
References _gainBucket, _vertexArray, getNumPartitions(), and GBPQueue< BPQNode >::pushBack().
Vertex * FMKWayGainMgr4::select (FMMoveInfo & moveInfo, const std::vector< unsigned char > & part, KWayConstrMgr3 & constrMgr)
Returns:
the next "best" vertex that satisfies all constraints when it is moved. Return also move from where to where.
References GBPQueueCursor< BPQNode >::getNext(), GBPQueueCursor< BPQNode >::hasNext(), GBPQueueCursor< BPQNode >::reset(), and BiConstrMgr3::satisfied().
void FMKWayGainMgr4::updateGain (const std::vector< unsigned char > & part, std::vector< short > * gain) [inline]
Update the gain structure according to the current gain.
References init().
void FMKWayGainMgr4::updateMove (const FMMoveInfo & moveInfo, const short * = 0) [inline]
Update the changes according to the move of vertex v from fromPart to toPart
References FMMoveInfo::_fromPart, _gainBucket, FMMoveInfo::_i_v, _vertexArray, GBPQueue< BPQNode >::detach(), and getNumPartitions().
void FMKWayGainMgr4::updateNeighbor (unsigned int whichPart, unsigned int i_w, const short * deltaGain) [inline]
Update the gain changes of the neighbor vertex in whichPart
Parameters:
whichPart in which partition
i_w the affected neighbor vertex
deltaGain the gain changes
References _cellList, _gainBucket, _vertexArray, getNumPartitions(), and GBPQueue< BPQNode >::modifyKeyLIFOBy().
Member Data Documentation
Cell* const FMKWayGainMgr4::_cellList [protected]
Cell array offset
Referenced by updateNeighbor().
VertexPQ FMKWayGainMgr4::_gainBucket[_M][_M] [protected]
gain bucket for each partition
Referenced by FMKWayGainMgr4(), getGain(), pushBack(), updateMove(), and updateNeighbor().
VertexPQCur FMKWayGainMgr4::_gainBucketCur[_M][_M] [protected]
gain bucket cursor
Referenced by FMKWayGainMgr4().
Netlist& FMKWayGainMgr4::_H [protected]
netlist hypergraph
Referenced by FMKWayGainMgr4().
unsigned int FMKWayGainMgr4::_K [protected]
number of partitions
Referenced by FMKWayGainMgr4(), and getNumPartitions().
std::vector<Vertex> FMKWayGainMgr4::_vertexArray[_M] [protected]
keep the data struct for the algo.
Referenced by FMKWayGainMgr4(), getGain(), pushBack(), updateMove(), and updateNeighbor().
The documentation for this class was generated from the following files:
FMKWayGainMgr4.hpp
FMBiGainMgr.cpp
FMKWayGainMgr2.cpp
FMKWayGainMgr4.cpp