KWayConstrMgrBase Class Reference
KWayConstrMgrBase Class Reference
Multi-Way Partitioner Core Engine
#include <KWayConstrMgrBase.hpp>
Public Member Functions
int getMaxDiff () const
int getAllowDiff () const
int getUpperBound () const
int getLowerBound () const
void setUpperBound (int upperBound)
void setLowerBound (int lowerBound)
boost::array< int, 64 > & getDiff ()
const boost::array< int, 64 > & getDiff () const
void setDiff (const boost::array< int, 64 > &diff)
void setDiff2 (const boost::array< int, 64 > &diff)
void updateMove (const FMMoveInfo &moveInfo)
bool satisfiedAll (const boost::array< int, 64 > &diff)
bool satisfiedOK ()
bool satisfiedAll ()
bool toOk (unsigned int k) const
bool fromOk (unsigned int k) const
Protected Member Functions
KWayConstrMgrBase (unsigned int K)
~KWayConstrMgrBase ()
unsigned int getNumPartitions () const
Protected Attributes
boost::array< int, 64 > _diff
temporary diff during one FM pass
unsigned int _K
number of partitions
int _upperBound
allowed upperbound
int _lowerBound
allowed lowerbound
bool _knownSatisfiedAll
whether the partitions are legalized
Static Protected Attributes
static const unsigned int _M = 64
Detailed Description
Multi-Way Constraints Management Base Class. Mainly to answer question "Is a vertex allowed to move from one partition to another?"
Constructor & Destructor Documentation
KWayConstrMgrBase::KWayConstrMgrBase (unsigned int K) [inline, protected]
Constructor
KWayConstrMgrBase::~KWayConstrMgrBase () [inline, protected]
Destructor
Member Function Documentation
int KWayConstrMgrBase::getAllowDiff () const [inline]
Returns:
allowed difference
References _lowerBound, and _upperBound.
boost::array<int,64>& KWayConstrMgrBase::getDiff () [inline]
Returns:
the difference between the partitions
References _diff.
const boost::array<int,64>& KWayConstrMgrBase::getDiff () const [inline]
Returns:
the difference between the partitions
References _diff.
int KWayConstrMgrBase::getLowerBound () const [inline]
Returns:
the allowed lower bound
References _lowerBound.
int KWayConstrMgrBase::getMaxDiff () const
Returns:
the maximum difference
References _diff, and getNumPartitions().
unsigned int KWayConstrMgrBase::getNumPartitions () const [inline, protected]
Returns:
the number of partitions.
References _K.
Referenced by getMaxDiff(), satisfiedAll(), and setDiff2().
int KWayConstrMgrBase::getUpperBound () const [inline]
Returns:
the allowed upper bound
References _upperBound.
bool KWayConstrMgrBase::satisfiedAll (const boost::array< int, 64 > & diff) [inline]
Returns:
true if current status is OK. In the current implement, only need to check the cell area constraint (cell weight). In the future, we may add other constraints such as #terminal on each partition.
References _knownSatisfiedAll, _lowerBound, _upperBound, and getNumPartitions().
bool KWayConstrMgrBase::satisfiedAll () [inline]
Returns:
true if current status is OK. In the current implement, only need to check the cell area constraint (cell weight). In the future, we may add other constraints such as #terminal on each partition.
References _diff, and satisfiedAll().
Referenced by KWayConstrMgr3::satisfied(), satisfiedAll(), and satisfiedOK().
bool KWayConstrMgrBase::satisfiedOK () [inline]
Returns:
true if current status is OK. In the current implement, only need to check the cell area constraint (cell weight). In the future, we may add other constraints such as #terminal on each partition.
References satisfiedAll().
void FMKWayPartMgrBase::setDiff (const boost::array< int, 64 > & diff) [inline]
Set the difference between the partitions
References _knownSatisfiedAll, and setDiff2().
void FMKWayPartMgrBase::setDiff2 (const boost::array< int, 64 > & diff) [inline]
Set the difference between the partitions
References _diff, and getNumPartitions().
Referenced by setDiff().
void KWayConstrMgrBase::setLowerBound (int lowerBound) [inline]
Set the allowed lower bound
References _lowerBound.
void KWayConstrMgrBase::setUpperBound (int upperBound) [inline]
Set the allowed upper bound
References _upperBound.
void KWayConstrMgrBase::updateMove (const FMMoveInfo & moveInfo) [inline]
Update the difference structure when v moves
References FMMoveInfo::_cell, _diff, FMMoveInfo::_fromPart, FMMoveInfo::_toPart, and Cell::getWeight().
The documentation for this class was generated from the following files:
KWayConstrMgrBase.hpp
FMKWayPartMgrBase.cpp
KWayConstrMgrBase.cpp