FMBiPartCore4 Class Reference
FMBiPartCore4 Class Reference
Bi-partitioner Core Engine
#include <FMBiPartCore4.hpp>
Public Member Functions
template<class MoveStruct >
void updateMove (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, MoveStruct &ms)
template<class GainTmpl >
void updateMove4 (const vector< unsigned char > &part, const FMMoveInfo &moveInfo, GainTmpl &gainMgr)
Protected Member Functions
FMBiPartCore4 (const FMParam &param)
virtual ~FMBiPartCore4 ()
void initGainCore (const std::vector< unsigned char > &part)
template<class GainTmpl >
void updateMove4 (const std::vector< unsigned char > &part, const FMMoveInfo &moveInfo, GainTmpl &gainMgr)
template<class GainTmpl >
void pushBack4 (unsigned int whichPart, const Cell &v, GainTmpl &gainMgr)
void updateNetStatus ()
Detailed Description
FM Bi-partitioning Manager Core (version 4). This version is tailered for refinement bi-partitioning manager in multi-level method.
Constructor & Destructor Documentation
FMBiPartCore4::FMBiPartCore4 (const FMParam & param) [protected]
Constructor
References FMPartMgrBase::getNumNets().
virtual FMBiPartCore4::~FMBiPartCore4 () [inline, protected, virtual]
Constructor
Member Function Documentation
void FMBiPartCore4::initGainCore (const std::vector< unsigned char > & part) [protected]
Setup the initial gain. Take O(n) time.
template<class GainTmpl > void FMBiPartCore4::pushBack4 (unsigned int whichPart, const Cell & v, GainTmpl & gainMgr) [inline, protected]
Push back the vertex to the gain manager (special for refinement code)
References FMPartMgrBase::_cellList, and FMBiPartComm::_gain.
template<class MoveStruct > void FMBiPartCore4::updateMove (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, MoveStruct & ms)
When the cell v is moved from fromPart, update the gains and the gain structures of its neighbors. (c.f. Sarrafzadeh and Wong, page 39)
Parameters:
part current partition solution
ms gain related structre
References FMMoveInfo::_cell, FMMoveInfo::_fromPart, FMPartMgrBase::_netList, FMBiPartComm::_num, FMMoveInfo::_toPart, PinForNetCursorTmpl< Net_, Pin_ >::count(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), Net::isHighFanout(), FMBiPartComm::updateMove2PinNet(), and FMBiPartComm::updateMoveGeneralNet().
template<class GainTmpl > void FMBiPartCore4::updateMove4 (const std::vector< unsigned char > & part, const FMMoveInfo & moveInfo, GainTmpl & gainMgr) [protected]
Update the gain structure given the moving vertex (special for refinement code)
template<class GainTmpl > void FMBiPartCore4::updateMove4 (const vector< unsigned char > & part, const FMMoveInfo & moveInfo, GainTmpl & gainMgr)
Update the gain structure given the moving vertex (special for refinement code)
References FMBiPartComm::_gain.
The documentation for this class was generated from the following files:
FMBiPartCore4.hpp
FMBiPartCore4.cpp