BiConstrMgrBase Class Reference
BiConstrMgrBase Class Reference
Bi-partitioner Core Engine
#include <BiConstrMgrBase.hpp>
Public Member Functions
int getMaxDiff () const
int getUpperBound () const
int getLowerBound () const
void setUpperBound (int upperBound)
void setLowerBound (int lowerBound)
int * getDiff ()
const int * getDiff () const
void setDiff (const int *diff)
void setDiff2 (const int *diff)
void updateMove (const FMMoveInfo &moveInfo)
bool satisfiedAll (const int *diff)
bool satisfiedOK ()
bool satisfiedAll ()
void resetKnownSatisfiedAll ()
Protected Member Functions
BiConstrMgrBase ()
~BiConstrMgrBase ()
Protected Attributes
int _diff [2]
temporary diff during one FM pass
int _upperBound
allowed upper bound
int _lowerBound
allowed lower bound
bool _knownSatisfiedAll
whether the partitions are legalized
Detailed Description
Bi-partitioning Constraints Management Base Class. Mainly to answer question "Is a vertex allowed to move from one partition to another?"
Constructor & Destructor Documentation
BiConstrMgrBase::BiConstrMgrBase () [inline, protected]
Constructor
BiConstrMgrBase::~BiConstrMgrBase () [inline, protected]
Destructor
Member Function Documentation
int* BiConstrMgrBase::getDiff () [inline]
Returns:
the difference between the partitions
References _diff.
const int* BiConstrMgrBase::getDiff () const [inline]
Returns:
the difference between the partitions
References _diff.
int BiConstrMgrBase::getLowerBound () const [inline]
Returns:
the allowed lower bound
References _lowerBound.
int BiConstrMgrBase::getMaxDiff () const [inline]
Returns:
the maximum difference
References _diff.
int BiConstrMgrBase::getUpperBound () const [inline]
Returns:
the allowed upper bound
References _upperBound.
bool BiConstrMgrBase::satisfiedAll (const int * diff) [inline]
Returns:
true if current status is OK. In the current implement, only need to check the cell area constraint (cell weight). In the future, we may add other constraints such as #terminal on each partition.
References _knownSatisfiedAll, _lowerBound, and _upperBound.
Referenced by FMKWayPartMgrBase::checkBalanceOk().
bool BiConstrMgrBase::satisfiedAll () [inline]
Returns:
true if current status is OK. In the current implement, only need to check the cell area constraint (cell weight). In the future, we may add other constraints such as #terminal on each partition.
References _diff, and satisfiedAll().
Referenced by satisfiedAll(), and satisfiedOK().
bool BiConstrMgrBase::satisfiedOK () [inline]
Returns:
true if current status is OK. In the current implement, only need to check the cell area constraint (cell weight). In the future, we may add other constraints such as #terminal on each partition.
References satisfiedAll().
void BiConstrMgrBase::setDiff (const int * diff) [inline]
Set the difference between the partitions
References _knownSatisfiedAll, and setDiff2().
void BiConstrMgrBase::setDiff2 (const int * diff) [inline]
Set the difference between the partitions
References _diff.
Referenced by setDiff().
void BiConstrMgrBase::setLowerBound (int lowerBound) [inline]
Set the allowed lower bound
References _lowerBound.
void BiConstrMgrBase::setUpperBound (int upperBound) [inline]
Set the allowed upper bound
References _upperBound.
void BiConstrMgrBase::updateMove (const FMMoveInfo & moveInfo) [inline]
Update the difference structure when v moves
References FMMoveInfo::_cell, _diff, FMMoveInfo::_fromPart, FMMoveInfo::_toPart, and Cell::getWeight().
The documentation for this class was generated from the following file:
BiConstrMgrBase.hpp