Netlist Class Reference
Netlist Class Reference
Data Modeling Group.
#include <Netlist.hpp>
Public Types
typedef GNode Vertex
typedef boost::shared_ptr
< Netlist > SPN
Public Member Functions
Netlist ()
~Netlist ()
void clear ()
void clearMasterList ()
void initVertexArray ()
Cell & getMaster (unsigned int id)
const Cell & getMaster (unsigned int id) const
Vertex & getVertex (unsigned int id)
const Vertex & getVertex (unsigned int id) const
Vertex * getVertexArray ()
unsigned int maximalMatchingNets (const std::vector< unsigned int > &netWeights)
bool maximalMatchingNetsOK ()
unsigned int minimumNetCover (const std::vector< unsigned int > &netWeights)
bool minimumNetCoverOK () const
unsigned int minimumNetCover2 (const std::vector< unsigned int > &netWeights)
unsigned int minimumNetCover3 (const std::vector< unsigned int > &netWeights)
unsigned int maximumIndependentSet (const std::vector< unsigned int > &netWeight)
bool maximumIndependentSetOK () const
unsigned int firstChoice (const std::vector< unsigned int > &netWeights)
unsigned int randomChoice ()
SPN contractByMMC ()
SPN contractByMMC2 ()
SPN contractByISC ()
SPN contractByFC ()
SPN contractByRandom ()
SPN contractByMMC (const std::vector< unsigned char > &part)
SPN contractByMMC2 (const std::vector< unsigned char > &part)
SPN contractByISC (const std::vector< unsigned char > &part)
SPN contractByFC (const std::vector< unsigned char > &part)
SPN contractByRandom (const std::vector< unsigned char > &part)
SPN contractCore (unsigned int numNetsSelected, const std::vector< unsigned char > &part)
void contractPhase2 (SPN subGraph)
bool contractCoreOK (const Netlist &subGraph) const
void clusterSize (std::vector< unsigned int > &netWeights) const
void projectUp (const Netlist &masterNl, std::vector< unsigned char > &partOut, const std::vector< unsigned char > &partIn) const
void projectDown (const Netlist &clusterNl, const std::vector< unsigned char > &partIn, std::vector< unsigned char > &partOut) const
int markHighFanOutNets ()
void markZeroPinNets ()
void markInterfaceNets (const std::vector< unsigned char > &part)
void setFixedNets (const std::vector< unsigned char > &part)
void setProxCells (int level)
void initWeightList (GDList< Vertex > &L)
bool isVILEOk (double bf, int numParts)
void pairWisePhase1 (const std::vector< unsigned char > &part, const std::vector< unsigned int > &groupMap, std::vector< Netlist * > &subGraphVec)
void pairWisePhase2 (const std::vector< unsigned char > &part, const std::vector< unsigned int > &groupMap, std::vector< Netlist * > &subGraphVec)
Detailed Description
A netlist class.
Constructor & Destructor Documentation
Netlist::Netlist ()
Constructor
Netlist::~Netlist ()
Destructor
References clear().
Member Function Documentation
void Netlist::clear ()
Reset to an empty Netlist
Reimplemented from NetlistBase.
Referenced by ~Netlist().
void Netlist::clearMasterList ()
Reset to an empty master list
void Netlist::clusterSize (std::vector< unsigned int > & netWeights) const
Create net weights by mean of the cluster size. Return the result to the array netWeights
Create net weights by mean of the cluster size. Return the result to the array netWeights. Net's weight is 0 if it is marked as fixed. (A net is marked as fixed if it is an interface net or it connects to a fixed cell.)
References NetlistBase::getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetlistBase::getNumNets(), Cell::getWeight(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), Cell::isFixed(), and Net::isFixed().
Referenced by NetlistTestCase::testMIS(), and NetlistTestCase::testMNC().
SPN Netlist::contractByFC () [inline]
Construct a coarsen graph based on the First-Choice clustering
References contractByFC().
Referenced by contractByFC(), and NetlistTestCase::testContraction().
SPN Netlist::contractByFC (const std::vector< unsigned char > & part)
Construct a coarsen graph based on the First-Choice clustering
SPN Netlist::contractByISC () [inline]
Construct a coarsen graph based on the independent set clustering
References contractByISC().
Referenced by contractByISC().
SPN Netlist::contractByISC (const std::vector< unsigned char > & part)
Construct a coarsen graph based on the independent set clustering
SPN Netlist::contractByMMC () [inline]
Construct a coarsen graph based on the minimal matching clustering
References contractByMMC().
Referenced by contractByMMC(), contractByMMC2(), NetlistTestCase::testContraction(), and NetlistTestCase::testProjection().
SPN Netlist::contractByMMC (const std::vector< unsigned char > & part)
Construct a coarsen graph based on the minimal matching clustering
SPN Netlist::contractByMMC2 () [inline]
Construct a coarsen graph based on the minimal matching clustering
References contractByMMC().
SPN Netlist::contractByMMC2 (const std::vector< unsigned char > & part)
Construct a coarsen graph based on the minimal matching clustering
SPN Netlist::contractByRandom () [inline]
Construct a coarsen graph based on the Random clustering
References contractByRandom().
Referenced by contractByRandom(), and NetlistTestCase::testContraction().
SPN Netlist::contractByRandom (const std::vector< unsigned char > & part)
Construct a coarsen graph based on the Random clustering
Netlist::SPN Netlist::contractCore (unsigned int numNetsSelected, const std::vector< unsigned char > & part)
Returns:
contraction netlist based on the result of net matching
Main Contraction. Todo: make the function shorter
References NetlistBase::_cellList, NetlistBase::_netList, NetlistBase::_numCells, NetlistBase::_numNets, NetlistBase::getNumCells(), and NetlistBase::getNumNets().
bool Netlist::contractCoreOK (const Netlist & subGraph) const
Verify if contractCore() is OK
void Netlist::contractPhase2 (Netlist::SPN sGPtr)
Complete the contraction process
References NetlistBase::getCostModel(), and NetlistBase::getTotalWeight().
Referenced by NetlistTestCase::testContraction(), and NetlistTestCase::testProjection().
unsigned int Netlist::firstChoice (const std::vector< unsigned int > & netWeights)
Find a set of candidate nets by FC algorithm. The nets selected are marked as visited.
Returns:
the number of nets selected. The algorithm starts with sorting nets in non-increasing order according to the net weights. Assume that net weights are bounded by a small value so that bucket sorting algorithm is used. In [khmetis], the aurthers commented that the rate of contractions by this method may be too fast. They imposed a constraint that the contraction process will stop if certain ratio is reach (1.7 in their case). In MLPart, similar constraint is set (1.3 in their case).
Note: This scheme creates less randomness than minimumNetCover.
References Net::clrVisited(), NetlistBase::getMaxDegree(), NetlistBase::getNet(), GDListCursor< DNode >::getNext(), NetlistBase::getNumNets(), GDListCursor< DNode >::hasNext(), Net::isFixed(), GBPQueue< BPQNode >::pushBackFast(), GBPQueue< BPQNode >::pushTo(), GBPQueue< BPQNode >::resync(), and Net::setVisited().
Cell& Netlist::getMaster (unsigned int id) [inline]
Returns:
master by index. Precondition: index within array bound.
const Cell& Netlist::getMaster (unsigned int id) const [inline]
Returns:
master by index. Precondition: index with array bound.
Vertex& Netlist::getVertex (unsigned int id) [inline]
Returns:
vertex by index. Precondition: index with array bound.
Referenced by initWeightList(), isVILEOk(), and minimumNetCover().
const Vertex& Netlist::getVertex (unsigned int id) const [inline]
Returns:
vertex by index. Precondition: index with array bound.
Vertex* Netlist::getVertexArray () [inline]
Returns:
Vertex array pointer
Referenced by CycleRemovalServ::CycleRemovalServ().
void Netlist::initVertexArray ()
Initialize the vertexArray.
References NetlistBase::_numCells.
Referenced by FMBiPartComm::FMBiPartComm(), FMKWayPartComm::FMKWayPartComm(), and minimumNetCover().
void Netlist::initWeightList (GDList< Vertex > & L)
Sort the cells in decending order according to their weight and return the result to L.
Sort the vertices by weight in descending order. Return result to the list L. If the kinds of weights are small (because the cells are from only a few master copies), then the function runs in nearly linear time. The worst case is O(N logN) time.
References GDList< DNode >::concat(), NetlistBase::getCell(), NetlistBase::getNumCells(), getVertex(), Cell::getWeight(), and Cell::isFixed().
Referenced by isVILEOk(), and minimumNetCover().
bool Netlist::isVILEOk (double balTol, int numParts)
Returns:
true if this netlist can eventually guarantee provide legal partition by FM iteration
Check if FM iteration can guarantee eventually produce legal solution with any (include illegal) initial partitions. The bound can be calculated by using a simple pigeonhole arugument. That is, if we want to gurantee a sequence of single moves can eventually produce legal result, at least sum of certain "small" vertices/cells has to be larger than the total weight divided by the number of partitions. This checking runs in O(N logN) where N is the number of vertices. (Assume no fixed cells)
References NetlistBase::getCell(), GDListCursor< DNode >::getNext(), NetlistBase::getTotalWeight(), getVertex(), Cell::getWeight(), GDListCursor< DNode >::hasNext(), and initWeightList().
int Netlist::markHighFanOutNets ()
Mark high fanout nets as FIXED. Otherwise mark as UNFIXED. Take O(m) time.
Mark a net as fixed if it is a high-fanout net. Otherwise, mark it as unfixed.
Returns:
the number of such nets.
References Net::clrFixed(), NetlistBase::getNet(), NetlistBase::getNumNets(), Net::isHighFanout(), and Net::setFixed().
void Netlist::markInterfaceNets (const std::vector< unsigned char > & part)
Mark nets as FIXED if they are in different partitions. Otherwise, mark as UNFIXED. Take O(m) time.
void Netlist::markZeroPinNets ()
Mark nets as FIXED if they do not connected to any unvisited cells. Take O(m) time.
Mark a net as fixed if it does not connect to any unvisited cells
References NetlistBase::getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetlistBase::getNumNets(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), Net::isFixed(), Cell::isVisited(), and Net::setFixed().
unsigned int Netlist::maximalMatchingNets (const std::vector< unsigned int > & netWeights)
Find a maximal matching of nets (edges) , i.e., a subset such that no two nets in shares a common cell (endpoint) and every net in shares at least a common cell with some net in .A cell that does not connect to any nets in is called isolated cell. A net weight is the sum of cell weight here. The objective is to minimize the total net weights.
First, we explore a similar Primal-Dual algorithm described in [1] that solves the graph weighted vertex cover problem. We generalize the idea of the algorithm for hypergraph. Instead of vertex cover, here we find the hyperedge cover , i.e., a subset such that, for each cell, at least one of connected nets belongs to . Then based on the solution of hyperedge cover, we perform the post processing such that no two nets in share a common cell by removing nets or moving nets. The process can be performed locally.
The overall run time is linear, assuming that the maximum degree is bounded by a small value.
Parameters:
netWeights net weights
Returns:
number of nets selected
Reference [1]: Program 2.7 in "Complexity and Approximation: Combinatorial Optimization Problems and their Approximability Properties.
bool Netlist::maximalMatchingNetsOK ()
Verify if maximalMatchingNets() is OK. Note that isVisited flags may be marked/unmarked after calling this function.
unsigned int Netlist::maximumIndependentSet (const std::vector< unsigned int > & netWeight)
Maximize Independent Set (Nets) by greedy algorithm. Take O(N logN) time.
Find an independent set by Greedy algorithm. The nets selected are marked as visited.
Returns:
the number of nets selected. The algorithm starts with sorting nets in non-increasing order first according to the net weights. Assume that net weights are bounded by a small value so that bucket sorting algorithm is used.
References Net::clrVisited(), NetlistBase::clrVisitedAllNets(), GDList< DNode >::detach(), NetlistBase::getNet(), GDListCursor< DNode >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetlistBase::getNumNets(), GDListCursor< DNode >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), GDList< DNode >::isEmpty(), Net::isFixed(), Net::isVisited(), maximumIndependentSetOK(), GDList< DNode >::popBack(), GDList< DNode >::pushBack(), GBPQueue< BPQNode >::pushBackFast(), GBPQueue< BPQNode >::pushTo(), GBPQueue< BPQNode >::resync(), and Net::setVisited().
Referenced by NetlistTestCase::testMIS().
bool Netlist::maximumIndependentSetOK () const
Verify if maximumIndependentSet() is OK. Take O(n) time.
Verify if minimumIndependentSet() is OK
References NetlistBase::getCell(), and NetlistBase::getNumCells().
Referenced by maximumIndependentSet(), and NetlistTestCase::testMIS().
unsigned int Netlist::minimumNetCover (const std::vector< unsigned int > & netWeights)
Find a minimum net (edge) cover , i.e., a subset such that for each cell, at least one of connected nets belongs to . A net weight is the sum of cell weight here. The objective is to minimize the total net weights. We explore a similar Primal-Dual algorithm described in [1] that solves the graph weighted vertex cover problem. We generalize the idea of the algorithm for hypergraph. Instead of vertex cover, here we find the hyperedge cover. The overall run time is linear, assuming that the maximum degree is bounded by a small value. The solution by the Primal-Dual algorithm is guaranteed bounded by times the optimal solution where is the maximum degree of nets.
Parameters:
netWeights net weights
Returns:
number of nets selected
Reference [1]: Program 2.7 in "Complexity and Approximation: Combinatorial Optimization Problems and their Approximability Properties.
Find a minimum net (edge) cover E'', i.e., a subset E'' E such that for each cell, at least one of connected nets belongs to E''. A net weight is the sum of cell weight here. The objective is to minimize the total net weights. We explore a similar Primal-Dual algorithm described in [1] that solves the graph weighted vertex cover problem. We generalize the idea of the algorithm for hypergraph. Instead of vertex cover, here we find the hyperedge cover. The overall run time is linear, assuming that the maximum degree is bounded by a small value. The solution by the Primal-Dual algorithm is guaranteed bounded by K times the optimal solution where K is the maximum degree of nets.
Input: Netlist H unsigned int Cell::weight Output: bool Net::isVisited Modified: bool Cell::isVisited (all covered)
Returns:
: number of nets selected
Reference [1]: Program 2.7 in "Complexity and Approximation: Combinatorial Optimization Problems and their Approximability Properties."
References NetlistBase::clrVisitedAllNets(), GDList< DNode >::detach(), NetlistBase::getCell(), NetlistBase::getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), getVertex(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), initVertexArray(), initWeightList(), GDList< DNode >::isEmpty(), Net::isFixed(), Cell::isVisited(), Net::isVisited(), minimumNetCoverOK(), GDList< DNode >::popBack(), Net::setVisited(), and Cell::setVisited().
Referenced by NetlistTestCase::testMNC().
unsigned int Netlist::minimumNetCover2 (const std::vector< unsigned int > & netWeights)
Find a minimum net (edge) cover. This version uses Maximum Adjacency (MA) ordering instead of random ordering.
See also:
maximumNetCover
References Cell::clrVisited(), NetlistBase::clrVisitedAllNets(), GDList< DNode >::detach(), NetlistBase::getCell(), NetlistBase::getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetCursorTmpl< Net_, Cell_, Pin_ >::getNext(), NetlistBase::getNumCells(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), PinForCellCursorTmpl< Cell_, Pin_ >::hasNext(), GDList< DNode >::isEmpty(), Net::isFixed(), Cell::isFixed(), Cell::isVisited(), Net::isVisited(), minimumNetCoverOK(), GDList< DNode >::popFront(), GDList< DNode >::pushBack(), Net::setVisited(), and Cell::setVisited().
bool Netlist::minimumNetCoverOK () const
Verify if minimumNetCover() is OK. Take O(n+m) time.
Verify if minimumNetCover() is OK
References NetlistBase::getCell(), NetlistBase::getNumCells(), and Cell::isFixed().
Referenced by minimumNetCover(), minimumNetCover2(), and NetlistTestCase::testMNC().
void Netlist::projectDown (const Netlist & clusterNl, const std::vector< unsigned char > & partIn, std::vector< unsigned char > & partOut) const
Project the result to the coarser level
Project the vertex value from the coarser hypergraph. The current netlist is a finer hypergraph
References NetlistBase::getCell(), NetlistBase::getNumCells(), and Cell::isFixed().
Referenced by NetlistTestCase::testProjection().
void Netlist::projectUp (const Netlist & masterNl, std::vector< unsigned char > & partOut, const std::vector< unsigned char > & partIn) const
Project the result to the finer level
Project the result to the coarser level (i.e. current level). Note that this function is valid after calling the contraction functions such as contractByMMC(), AND before calling the contractPhase2() function.
References Node::firstAdjPin(), Pin::getCell(), NetlistBase::getCell(), Pin::getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetlistBase::getNumCells(), Cell::isCluster(), and Cell::isFixed().
void Netlist::setFixedNets (const std::vector< unsigned char > & part)
Mark nets as FIXED if they are in different partitions
Mark a net as fixed if it is an interface net. Otherwise, mark it as unfixed.
References Net::clrFixed(), NetlistBase::getCell(), NetlistBase::getNet(), CellCursorTmpl< Cell_, Net_, Pin_ >::getNext(), NetlistBase::getNumNets(), PinForNetCursorTmpl< Net_, Pin_ >::hasNext(), and Net::setFixed().
Referenced by NetlistTestCase::testProjection().
void Netlist::setProxCells (int level)
Set "Proximity level"
Mark cells unfixed according to the proximity level.
References Cell::clrFixed(), NetlistBase::clrVisitedAllCells(), NetlistBase::clrVisitedAllNets(), NetlistBase::getCell(), NetlistBase::getNumCells(), Cell::isFixed(), Cell::isVisited(), and Cell::setVisited().
The documentation for this class was generated from the following files:
Netlist.hpp
Netlist.cpp