Bi-partitioner Core Engine
Bi-partitioner Core Engine
Partitioning Group.
Classes
class BiConstrMgr
class BiConstrMgr3
class BiConstrMgrBase
class FMBiGainArray
class FMBiGainMgr
class FMBiGainMgr2
class FMBiGainMgr3
class FMBiPartComm
class FMBiPartCore
class FMBiPartCore4
class FMBiPartMgrBase
Functions
FMBiGainMgr::FMBiGainMgr (const FMParam &param)
void FMBiGainMgr::init (const std::vector< unsigned char > &, const std::vector< short > &gain)
void FMBiGainMgr::init (const std::vector< short > &gain)
Vertex * FMBiGainMgr::select (FMMoveInfo &moveInfo, const std::vector< unsigned char > &part, const BiConstrMgr3 &constraintMgr)
int FMBiGainMgr::getGain (const FMMoveInfo &moveInfo) const
void FMBiGainMgr::updateMove (const FMMoveInfo &moveInfo)
void FMBiGainMgr::updateNeighbor (unsigned int, unsigned int i_w, short deltaGain)
void FMBiGainMgr::pushBack (unsigned int, const Cell &v, short gain)
void FMBiGainMgr::updateGain (const std::vector< unsigned char > &, const std::vector< short > &gain)
void FMBiGainMgr3::updateNeighbor (unsigned int whichPart, unsigned int i_w, short deltaGain)
Detailed Description
This module contains the implementation of Fiduccia-Mattheyses bipartitioning algorithm and its variants. Bi-partitioning problem is a special case of $k$-way partitioning problem where $k$ is equal to 2. When a vertex moves from 0, it implies that the vertex will move to 1. Similarly, when a vertex move to 1, it implies that the vertex moves from 0. Implementation can take the advantage of these facts in order to make the program runs faster than the general k-way implementation. Also, different cost models such as (k-1) metric, SOED metric and hyperedge metric are the same in the bi-partitioning problem.
Function Documentation
FMBiGainMgr::FMBiGainMgr (const FMParam & param) [inherited]
Constructor
References GBPQueueCursor< BPQNode >::associate(), NetlistBase::getMaxDegree(), and GBPQueue< BPQNode >::setUp().
int FMBiGainMgr::getGain (const FMMoveInfo & moveInfo) const [inline, inherited]
Returns:
the gain of vertex if it moves
References FMMoveInfo::_i_v, and GBPQueue< BPQNode >::getKey().
void FMBiGainMgr::init (const std::vector< unsigned char > & , const std::vector< short > & gain) [inline, inherited]
Setup the gain bucket structure
Referenced by FMBiGainMgr::updateGain().
void FMBiGainMgr::init (const std::vector< short > & gain) [inherited]
Setup the gain bucket structure
void FMBiGainMgr::pushBack (unsigned int, const Cell & v, short gain) [inline, inherited]
Push back the cell to gain bucket. Precondition: v is not in bucket.
References GBPQueue< BPQNode >::pushBack().
Vertex* FMBiGainMgr::select (FMMoveInfo & moveInfo, const std::vector< unsigned char > & part, const BiConstrMgr3 & constraintMgr) [inherited]
Select the next "best" vertex that satisfies all constraints when it is moved.
void FMBiGainMgr::updateGain (const std::vector< unsigned char > & , const std::vector< short > & gain) [inline, inherited]
Update the gain structure according to the freeVertexList.
References FMBiGainMgr::init().
void FMBiGainMgr3::updateNeighbor (unsigned int whichPart, unsigned int i_w, short deltaGain) [inline, inherited]
Update the neighbor of the moved cells due to the move.
Reimplemented from FMBiGainMgr2.
References FMBiGainMgr2::_cellList, FMBiGainMgr2::_gainBucket, FMBiGainMgr2::_vertexArray, and GBPQueue< BPQNode >::modifyKeyBy().
void FMBiGainMgr::updateNeighbor (unsigned int , unsigned int i_w, short deltaGain) [inline, inherited]
Update the gain information by deltaGain amount
References GBPQueue< BPQNode >::modifyKeyLIFOBy().